export enum facultyEnum {
  EDU = 'Education',
  PSY = 'Psychology',
  DENT = 'Dentistry',
  LAW = 'Law',
  COMMARTS = 'Communication Arts',
  CBS = 'Commerce and Business Administration',
  MD = 'Medicine',
  PHARM = 'Pharmacy',
  POLSCI = 'Political Science',
  SCI = 'Science',
  SPSC = 'Sports Science',
  ENG = 'Engineering',
  FAA = 'Fine and Applied Arts',
  ECON = 'Economics',
  ARCH = 'Architecture',
  AHS = 'Allied Health Sciences',
  VET = 'Veterinary Medicine',
  ARTS = 'Arts',
  SCII = 'Arts and Science in Integrated Innovation',
  CUSAR = 'Integrated Agricultural'
}

export const faculties = [
  { th: 'ครุศาสตร์', facultyEnum: facultyEnum.EDU  },
  { th: 'จิตวิทยา', facultyEnum: facultyEnum.PSY  },
  { th: 'ทันตแพทยศาสตร์', facultyEnum: facultyEnum.DENT  },
  { th: 'นิติศาสตร์', facultyEnum: facultyEnum.LAW  },
  { th: 'นิเทศศาสตร์', facultyEnum: facultyEnum.COMMARTS  },
  { th: 'พาณิชยศาสตร์และการบัญชี', facultyEnum: facultyEnum.CBS  },
  { th: 'แพทยศาสตร์', facultyEnum: facultyEnum.MD  },
  { th: 'เภสัชศาสตร์', facultyEnum: facultyEnum.PHARM  },
  { th: 'รัฐศาสตร์', facultyEnum: facultyEnum.POLSCI  },
  { th: 'วิทยาศาสตร์', facultyEnum: facultyEnum.SCI  },
  { th: 'วิทยาศาสตร์การกีฬา', facultyEnum: facultyEnum.SPSC  },
  { th: 'วิศวกรรมศาสตร์', facultyEnum: facultyEnum.ENG  },
  { th: 'ศิลปกรรมศาสตร์', facultyEnum: facultyEnum.FAA  },
  { th: 'เศรษฐศาสตร์', facultyEnum: facultyEnum.ECON  },
  { th: 'สถาปัตยกรรมศาสตร์', facultyEnum: facultyEnum.ARCH  },
  { th: 'สหเวชศาสตร์', facultyEnum: facultyEnum.AHS  },
  { th: 'สัตวแพทยศาสตร์', facultyEnum: facultyEnum.VET  },
  { th: 'อักษรศาสตร์', facultyEnum: facultyEnum.ARTS  },
  { th: 'สถาบันนวัตกรรมบูรณาการแห่งจุฬาฯ (BAScii)', facultyEnum: facultyEnum.SCII  },
  { th: 'คณะเกษตรศาสตร์บูรณาการ', facultyEnum: facultyEnum.CUSAR  }
]

