import { FacultyType } from './faculty'

export interface Workshop {
  id: string
  name: string
  description: string
  hasPreregistered: boolean
  hasLimitParticipants: boolean
  url?: string
  faculty: FacultyType
  timeSlot?: string // separated by /
  owner?: string
  locationName?: string
  locationURL?: string
}

export const WORKSHOP_DATA: Workshop[] = [
  // คณะครุศาสตร์
  {
    id: 'eduw1',
    name: 'การแข่งขันวิชาการและความเป็นเลิศทางวิทยาศาสตร์ ระดับมัธยมศึกษาตอนปลาย (คิดวิทย์ วิชาการ)',
    description:
      'การแข่งขันตอบปัญหาวิทยาศาสตร์ ประเภททีม 3 คน โดยมีขอบเขตของเนื้อหาในรายวิชาฟิสิกส์ เคมี และชีววิทยา ระดับชั้นมัธยมศึกษาตอนปลาย จาก หนังสือสถาบันส่งเสริมการสอนวิทยาศาสตร์และเทคโนโลยี (สสวท.) เป็นแหล่งอ้างอิง',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/kitwiz.edu.cu',
    faculty: 'edu',
  },
  {
    id: 'eduw2',
    name: 'การแข่งขัน HIGH S-KRU DEBATE: The Second Competition การแข่งขันโต้วาที ระดับมัธยมศึกษาตอนปลาย ครั้งที่ 2',
    description:
      'การแข่งขันโต้วาที โดนรอบคัดเลือกเป็นการแสดงทรรศนะในหัวข้อ “สมควรสร้างสุขภาพใจทั่วหน้าให้กับนักเรียนในไทย” และในรอบ 8 ทีมสุดท้าย รอบ 4 ทีมสุดท้าย และรอบชิงชนะรองชนะเลิศอันดับ 2 และรอบชนะเลิศ เป็นการแข่งขันโต้วาที แสดงทรรศนะภายใต้ญัตติเกี่ยวกับการศึกษา',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/edu_cooldebate',
    faculty: 'edu',
  },
  {
    id: 'eduw3',
    name: 'การแข่งขันการประกวดอ่านออกเสียงภาษาไทย เฉลิมพระเกียรติพระบาทสมเด็จพระมงกุฎเกล้าเจ้าอยู่หัว เนื่องในวาระครบ 100 ปี วันสวรรคต พุทธศักราช 2568',
    description:
      'การแข่งขันประกวดอ่านออกเสียงภาษาไทยทั้งร้อยแก้วและร้อยกรอง (ทำนองเสนาะ) จากบทพระราชนิพนธ์ในพระบาทสมเด็จพระมงกุฎเกล้าเจ้าอยู่หัว ซึ่งจะแบ่งรอบการแข่งขันเป็นรอบคัดเลือก และรอบชิงชนะเลิศ',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/th_langandcult',
    faculty: 'edu',
  },
  {
    id: 'eduw4',
    name: 'ซุ้มวิชาเอก',
    description:
      'การนำเสนอข้อมูลพื้นฐานที่เกี่ยวข้องกับวิชาเอก โดยนำเสนอ 3 ประเด็น คือ การรับสมัครเข้าศึกษาต่อ ภาพรวมของการเรียนภายในวิชาเอก รายวิชาและกิจกรรมที่น่าสนใจ และในแต่ละวิชาเอกจะมีการจัดกิจกรรม หรือ workshop ที่เกี่ยวข้องกับสาขาวิชาเอก 20 ซุ้ม จัดแสดง ณ ห้องสุมน อมรวิวัฒน์ และห้องลีลาวดี',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/educu.openhouse',
    faculty: 'edu',
  },
  {
    id: 'eduw5',
    name: 'นิทรรศการ',
    description:
      'นำเสนอนวัตกรรมทางการศึกษาที่พัฒนาโดยนิสิตและบุคลากรคณะครุศาสตร์ ซึ่งเป็นนวัตกรรมที่มุ่งพัฒนาและแก้ไขปัญหาที่เกิดขึ้นในกระบวนการเรียนรู้และระบบการศึกษาไทย และประชาสัมพันธ์ทุนการศึกษาภายในคณะ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/educu.openhouse',
    faculty: 'edu',
  },
  {
    id: 'eduw6',
    name: 'กิจกรรมกลาง',
    description:
      'กิจกรรม Workshop เกี่ยวกับการทำความรู้จักกับวิชาชีพครู หน้าที่ของครูเมื่อประกอบอาชีพครู รวมไปถึงกิจกรรมที่ออกแบบให้สอดคล้องกับวิชาครูที่ได้เรียนในคณะครุศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/educu.openhouse',
    faculty: 'edu',
  },
  {
    id: 'eduw7',
    name: 'เวทีกลาง',
    description:
      'การเสวนาวิชาการ และเป็นพื้นที่แสดงศักยภาพของนักเรียนโรงเรียนสาธิตจุฬาลงกรณ์มหาวิทยาลัย และนิสิตคณะครุศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย ผ่านการแสดงต่าง ๆ ติดตามรายละเอียดเพิ่มเติมได้ที่ Instagram : educu.openhouse',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/educu.openhouse',
    faculty: 'edu',
  },
  // คณะจิตวิทยา
  {
    id: 'psyw1',
    name: 'The Psyche’s Symphony college (ซุ้มสอบเข้า)',
    description:
      'เป็นซุ้มแนะแนวข้อมูลการสอบเข้าของคณะจิตวิทยาทั้ง2ภาค ( ภาคไทยและภาคอินเตอร์ ) อย่างละเอียด ภายในซุ้มจะมีรายละเอียดของเกณฑ์การรับ ข้อมูลเอกสารที่ต้องยื่น ฯลฯ เพื่อให้ผู้เข้าร่วมได้เตรียมความพร้อมหากมีความสนใจจะเรียนต่อในคณะจิตวิทยา พร้อมทั้งยังแสดงเอกลักษณ์ของทั้งสองภาคเพื่อให้ผู้เข้าร่วมได้เข้าใจถึงความแตกต่างของแต่ละภาคและตัดสินใจเลือกภาควิชาที่เหมาะกับตนเองได้ดียิ่งขึ้น',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/psychecu.openhouse',
    faculty: 'psy',
  },
  {
    id: 'psyw2',
    name: 'Psyche’s Zenith Route (ซุ้มคณะ)',
    description:
      'เป็นซุ้มแนะนำคณะและสาขาวิชาจิตวิทยาที่เรียนเบื้องต้น ได้แก่ จิตวิทยาพัฒนาการ จิตวิทยาปริชาน จิตวิทยาคลินิก จิตวิทยาการปรึกษา จิตวิทยาสังคม จิตวิทยาอุตสาหกรรมและองค์กรณ์ เพื่อให้ผู้เข้าร่วมได้เห็นภาพของการเรียนจิตวิทยามากขึ้น แต่ละสาขาวิชาจะมีการแนะนำการเรียนและยกตัวอย่างเนื้อหาการเรียนผ่านกิจกรรมที่น่าสนใจ รวมถึงแนะนำการสาขาที่ทางคณะจิตวิทยาเปิดสอนในระดับชั้นป.โทและเอก',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/psychecu.openhouse',
    faculty: 'psy',
  },
  {
    id: 'psyw3',
    name: 'The Lunar Mindscape (ซุ้ม Workshop)',
    description:
      'Workshop บูรณาการความรู้ทางจิตวิทยาสาขาต่าง ๆ ให้ผู้เข้าร่วมได้ลงมือทำจริง ผ่านกิจกรรมจำลองสถานการณ์และการสะท้อนคิด เพื่อเห็นภาพคณะจิตวิทยา และสามารถนำไปประยุกต์ใช้ในชีวิตประจำวันได้',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/psychecu.openhouse',
    faculty: 'psy',
  },
  // คณะทันตแพทยศาสตร์
  {
    id: 'dentw1',
    name: 'ฐานแล็บดัดลวด (Orthodontics Lab)',
    description:
      'หลายคนอาจจะไม่รู้ว่าลวดกับงานทันตกรรมเป็นอีกอย่างที่เป็นของคู่กัน โดยเฉพาะในงานจัดฟัน และงานทันตกรรมประดิษฐ์ มาลองฝึกดัดลวด ตั้งแต่แบบรูปพื้นฐาน ไปจนถึงชิ้นงานที่หมอฟันใช้กันจริง ๆ ได้แล้วที่แล็บดัดลวด!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.ticketmelon.com/dentcuopenhouse2026/lab-registration',
    faculty: 'dent',
    timeSlot:
      '08:50 - 09:30 / 09:40 - 10:20 / 10:30 - 11:10 / 11:20 - 12:00 / 12:50 - 13:30 / 13:40 - 14.20 / 14:30 - 15:10 / 15:20 - 16:00',
  },
  {
    id: 'dentw2',
    name: 'ฐานแล็บกรอฟัน-อุดฟัน',
    description:
      'หากเรานึกถึงงานของทันตแพทย์ สิ่งแรก ๆ ที่เรามักจะนึกถึงคือการอุดฟัน เพื่อรักษาฟันผุใช่มั้ยล่ะ! ในแล็บนี้จะให้น้อง ๆ ทุกคนจำลองตนเองเป็นทันตแพทย์  โดยจะได้ฝึกกรอฟันเอาฟันผุออกด้วยหัวกรอของทันตแพทย์ตัวจริง และได้อุดฟันด้วยวัสดุอุดจำลองด้วยนะ!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.ticketmelon.com/dentcuopenhouse2026/lab-registration',
    faculty: 'dent',
    timeSlot:
      '08:50 - 09:30 / 09:40 - 10:20 / 10:30 - 11:10 / 11:20 - 12:00 / 12:50 - 13:30 / 13:40 - 14.20 / 14:30 - 15:10 / 15:20 - 16:00',
  },
  {
    id: 'dentw3',
    name: 'ฐานแล็บตรวจฟัน (Indirect Vision &Ergonomics Lab)',
    description:
      'เคยสงสัยกันไหมว่า..หมอฟันตรวจฟันในมุมที่มองไม่เห็นของช่องปากคนไข้ได้ยังไง? หมอฟันจำเป็นต้องมีกระจกหรือ “mouth mirror” ไว้ช่วย! แล็บตรวจฟันจะสอนน้อง ๆ ใช้อุปกรณ์ตรวจฟันในหุ่นคนไข้จำลอง พร้อมด้วยวิธีนั่งที่เหมาะสมกับการทำงานของหมอฟันด้วย!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.ticketmelon.com/dentcuopenhouse2026/lab-registration',
    faculty: 'dent',
    timeSlot:
      '08:50 - 09:30 / 09:40 - 10:20 / 10:30 - 11:10 / 11:20 - 12:00 / 12:50 - 13:30 / 13:40 - 14.20 / 14:30 - 15:10 / 15:20 - 16:00',
  },
  {
    id: 'dentw4',
    name: 'ฐานแล็บเย็บแผล (Oral Surgery Lab)',
    description:
      'อีกหนึ่งการรักษาของหมอฟันที่แทบทุกคนต้องเจอสักครั้งในชีวิตอย่างการผ่าฟันคุด หมอฟันต้องทำการผ่าเหงือกเข้าไปเอาฟันออกมา สุดท้ายก็ต้องเย็บแผลที่ผ่าเหงือกเข้าไป เพราะฉะนั้นหมอฟันก็ต้องฝึกเย็บแผลด้วยนั่นเอง แล็บนี้เราจะพาน้อง ๆ มาฝึกเย็บแผล และได้เห็นว่าหมอฟันใช้อุปกรณ์อะไรและทำกันยังไงบ้าง!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.ticketmelon.com/dentcuopenhouse2026/lab-registration',
    faculty: 'dent',
    timeSlot:
      '08:50 - 09:30 / 09:40 - 10:20 / 10:30 - 11:10 / 11:20 - 12:00 / 12:50 - 13:30 / 13:40 - 14.20 / 14:30 - 15:10 / 15:20 - 16:00',
  },
  {
    id: 'dentw5',
    name: 'Tour Gross',
    description:
      'ทำไมทันตแพทย์ถึงต้องเรียนร่างกายมนุษย์กันนะ? มาศึกษา Histology ในกล้องจุลทรรศน์ และ Gross Anatomy ในร่างอาจารย์ใหญ่ และความสำคัญของการศึกษาร่างกายมนุษย์กับอาชีพทันตแพทย์',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 12:00 / 12:50 - 16:00',
  },
  {
    id: 'dentw6',
    name: 'Tour Clinic',
    description:
      'พี่ ๆ ชั้นปีคลินิกจะพาน้อง ๆ ไปดู "ยูนิต" หรือเก้าอี้ทำฟันที่ใช้รักษาคนไข้จริงแบบกลุ่มเล็ก ได้เห็นสภาพแวดล้อมการเรียนชั้นปี 4-6 ของนิสิตทันตะ รวมไปถึงเครื่องมือที่ใช้ในเคสรักษาที่ต่างกันออกไป และยังได้ลองปรับเก้าอี้ทำฟันด้วยตัวเองอีกด้วยนะ!',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 12:00 / 12:50 - 16:00',
  },
  {
    id: 'dentw7',
    name: 'นิทรรศการ',
    description:
      'จัดแสดงชีวิตนิสิตทันตะ จุฬาฯ 6 ชั้นปี ทั้งปีพรีคลินิกและปีคลินิก ทั้งเรื่องเรียน กิจกรรม และอื่น ๆ อีกมากมาย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 16:00',
  },
  {
    id: 'dentw8',
    name: 'Dent Talk',
    description:
      'Talk Show แชร์ประสบการณ์และคำแนะนำในหัวข้อต่าง ๆ โดยนิสิตปัจจุบันและนิสิตเก่าทันตะ จุฬาฯ ได้แก่ "ทันตะติดได้ ทำไงดีเอ่ย", "เรียนจบทั้งที ไปไหนต่อดีน้า", "วัน ๆ ของเด็กทันตะ", และ "ใต้เตียงทันตะ จุฬาฯ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot:
      'Sat: 10:30 - 11:30 / Sat: 12:50 - 14:20 / Sun: 9:40 - 11:10 / Sun: 12:50 - 14:20',
  },
  {
    id: 'dentw9',
    name: 'Consult',
    description:
      'ปรึกษาพี่ ๆ ทันตะ จุฬาฯ แบบ 1:1 หรือแบบกลุ่มเล็ก ทั้งเรื่องการสอบเข้า ประสบการณ์ต่าง ๆ และการเรียนในคณะทันตะ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 12:00 / 12:50 - 16:00',
  },
  {
    id: 'dentw10',
    name: 'พิพิธภัณฑ์ร่างกายมนุษย์',
    description:
      '1 ใน 11 พิพิธภัณฑ์ของโลกและพิพิธภัณฑ์แห่งแรกของเอเชียตะวันออกเฉียงใต้ ที่จัดแสดงร่างกายมนุษย์ด้วยเทคนิคพลาสติเนชัน จัดแสดงร่างกายและชิ้นส่วนมนุษย์แบบ 3 มิติ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 16:00',
  },
  {
    id: 'dentw11',
    name: 'พิพิธภัณฑสถานวาจวิทยาวัฑฒน์',
    description:
      'แหล่งรวบรวมสิ่งอ้างอิงทางประวัติศาสตร์ วิวัฒนาการที่หลากหลายทางทันตกรรมของไทย เป็นศูนย์รวมความรู้แก่ผู้ศึกษาทางทันตแพทย์ได้ใช้ประโยชน์ในการเรียนรู้และศึกษาค้นคว้า พิพิธภัณฑสถานแห่งนี้มีประวัติความเป็นมาที่ยาวนาน นับเป็นความภูมิใจของชาวทันตแพทศาสตร์ จุฬาฯ เป็นอย่างยิ่ง',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 16:00',
  },
  {
    id: 'dentw12',
    name: 'เพนต์ฟัน (Paint Fun)',
    description:
      'กิจกรรมเพนต์ฟันปูนที่เปิดให้น้อง ๆ ได้นั่งพักผ่อนหย่อนใจ วาดลวดลาย และระบายสีปูนปลาสเตอร์รูปฟันซึ่งสามารถนำกลับบ้านเป็นของที่ระลึกจาก DentCU Open House 2026 ได้อีกด้วยยย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/dentcuopenhouse',
    faculty: 'dent',
    timeSlot: '8:50 - 12:00 / 12:50 - 16:00',
  },
  // คณะนิติศาสตร์
  {
    id: 'laww1',
    name: 'นิทรรศการ',
    description:
      'มีการให้ความรู้ทางกฎหมาย ความหลากหลายทางอาชีพในสายนิติศาสตร์ และแนะนำชมรมภายในคณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/lawchulaopenhouse',
    faculty: 'law',
    timeSlot: '09:00 - 17:00',
    locationName:
      'Learning Space อาคารเทพทวารวดี คณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    locationURL: 'https://maps.app.goo.gl/tJokfjJPY3N4Ae5n8?g_st=ic',
  },
  {
    id: 'laww2',
    name: 'แนะแนวการศึกษา',
    description:
      'กิจกรรมแนะแนวการศึกษาทั้งในหลักสูตรนิติศาสตรบัณฑิตและหลักสูตร Bachelor of Laws, experiential learning in Business and Tech Law (LLBel) เพื่อค้นหาว่าตนเองเหมาะกับการเรียนในสาขาวิชา นิติศาสตร์หรือไม่ และเตรียมความพร้อมในการสอบเข้าศึกษาต่อในมหาวิทยาลัย',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/lawchulaopenhouse',
    faculty: 'law',
    timeSlot: '09:00 - 16:00',
    locationName:
      'ห้องอุกฤษฏ์ ชั้น 5, ห้องสุรเกียรติและห้องประชุมตรงข้ามห้องสุรเกียรติ ชั้น 4 อาคารเทพทวารวดี คณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    locationURL: 'https://maps.app.goo.gl/tJokfjJPY3N4Ae5n8?g_st=ic',
  },
  {
    id: 'laww3',
    name: 'Workshop',
    description:
      'กิจกรรม Workshop เพื่อเปิดโอกาสให้ผู้เข้าร่วมงานได้ลองฝึกทักษะการเรียนรู้ และการคิดวิเคราะห์ในทางกฎหมาย แบ่งเป็นสายการเรียน ได้แก่ สายกฎหมายธุรกิจและภาษีอากร สายกฎหมายแพ่งและอาญา สายกฎหมายมหาชน และ สายกฎหมายระหว่างประเทศ',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://docs.google.com/forms/d/1W2OqaYGGN1G5XRHWcYiFlmdnFYgdDjCgxlIqqVp0gWo/edit',
    faculty: 'law',
    timeSlot:
      '09:00 - 10:00 / 10:00 - 11:00 / 11:00 - 12:00 / 13:00 - 14:00 / 14:00 - 15:00 / 15:00 - 16:00',
    locationName:
      'ห้อง 605, 606, 904, 905 อาคารเทพทวารวดี คณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    locationURL: 'https://maps.app.goo.gl/tJokfjJPY3N4Ae5n8?g_st=ic',
  },
  {
    id: 'laww4',
    name: 'เวทีกลาง',
    description:
      'ในบริเวณเวทีกลาง มีการจัดกิจกรรมตลอดทั้งช่วงเช้าและช่วงบ่าย โดยกิจกรรมในช่วงเช้าเป็นการจัดทอล์คโชว์ตลอดระยะเวลา 2 วัน โดยมีนิสิตคณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัยร่วมเป็นวิทยากร นำเสนอประเด็นและหัวข้อที่แตกต่างกันในแต่ละวัน และกิจกรรมช่วงบ่ายเป็นกิจกรรมการแสดงจากหลากหลายชมรมภายในคณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย เพื่อแสดงถึงความวามหลากหลายของกิจกรรมที่จะเกิดขึ้นในรั้วคณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/lawchulaopenhouse',
    faculty: 'law',
    timeSlot: '08:00 - 16:00',
    locationName:
      'ลานอเนกประสงค์ อาคารเทพทวารวดี คณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    locationURL: 'https://maps.app.goo.gl/tJokfjJPY3N4Ae5n8?g_st=ic',
  },
  {
    id: 'laww5',
    name: 'ศาลจำลอง',
    description:
      'กิจกรรมศาลจำลองเพื่อให้ผู้ร่วมงาน ได้รู้จักและเห็นถึงกระบวนการในการประสาทความยุติธรรมของไทย แบ่งเป็น 2 รอบ รอบละ 60 คน และจะมีการถ่ายทอดสด ณ เวทีกลางร่วมด้วย',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://docs.google.com/forms/d/1W2OqaYGGN1G5XRHWcYiFlmdnFYgdDjCgxlIqqVp0gWo/edit',
    faculty: 'law',
    timeSlot: '10:00 - 12:00 / 13:00 - 15:00',
    locationName:
      'ห้อง 1205, 1005 อาคารเทพทวารวดี คณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย',
    locationURL: 'https://maps.app.goo.gl/tJokfjJPY3N4Ae5n8?g_st=ic',
  },
  // คณะนิเทศศาสตร์
  {
    id: 'commartsw1',
    name: 'Chitchat',
    description:
      'กิจกรรมที่ผู้เข้าร่วมงานสามารถพูดคุยสอบถามข้อมูลต่างๆกับนิสิตปัจจุบันได้อย่างใกล้ชิด ไม่ว่าจะเป็นเรื่องการสอบเข้า การเรียน กิจกรรม เเละการใช้ชีวิต',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/nitadecuopenhouse',
    faculty: 'commarts',
    locationName: 'อาคารมงกุฎสมมติวงศ์',
    locationURL: 'https://share.google/TAFTVpd3DXusV7K7l',
  },
  {
    id: 'commartsw2',
    name: 'Exhibition',
    description:
      'เนื้อหาภายในนิทรรศการจะมีการให้ข้อมูลเกี่ยวกับทุกภาควิชารวมถึงจุดถ่ายรูปน่ารักๆ ให้มาเช็คอิน นอกจากนิทรรศการหลักเเล้วจะมีการเเสดงผลงานจากนิสิตจากแต่ละภาควิชา (ไม่ทุกภาค) ให้เดินชมเช่นกัน',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/nitadecuopenhouse',
    faculty: 'commarts',
    timeSlot: '9:00 - 16:00',
    locationName: 'อาคารมงกุฎสมมติวงศ์',
    locationURL: 'https://share.google/TAFTVpd3DXusV7K7l',
  },
  {
    id: 'commartsw3',
    name: 'Showcase',
    description:
      'ผู้เข้าร่วมงานสามารถรับชมภาพยนตร์สั้นเเละผลงานในรูปแบบวิดิโอต่างๆที่สร้างโดยนิสิตคณะนิเทศศาสตร์ที่ห้อง screening room ของคณะ',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/nitadecuopenhouse',
    faculty: 'commarts',
    timeSlot: '9:00 - 16:00',
    locationName: 'อาคารมงกุฎสมมติวงศ์ ',
    locationURL: 'https://share.google/TAFTVpd3DXusV7K7l',
  },
  {
    id: 'commartsw4',
    name: 'Studio Room Tour',
    description:
      'กิจกรรมที่ทีมงานนิสิตคณะนิเทศศาสตร์จะพาผู้เข้าร่วมงานเดินชมห้อง studio ขนาดใหญ่รวมถึงห้อง control room ของคณะ โดยกิจกรรมนี้จะเปิดให้ผู้เข้าร่วมงานเดินชมเป็นรอบๆ',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/nitadecuopenhouse',
    faculty: 'commarts',
    locationName: 'อาคารมงกุฎสมมติวงศ์ ชั้น 1M ห้อง CART1 CDM2B',
    locationURL: 'https://share.google/TAFTVpd3DXusV7K7l',
  },
  {
    id: 'commartsw5',
    name: 'Workshop Film',
    description:
      'ผู้เข้าร่วมงานจะได้ลองลงมือทำกิจกรรมที่มีเนื้อหาเกี่ยวกับภาควิชาศิลปะภาพยนตร์ ตัวอย่างเช่น ฐานกิจกรรมอุปกรณ์กล้องเเละเสียง รายละเอียดโปรดติดตามเพิ่มเติม',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/nitadecuopenhouse',
    faculty: 'commarts',
    owner: 'ภาควิชาศิลปะภาพยนตร์',
    locationName: 'อาคารมงกุฎสมมติวงศ์',
    locationURL: 'https://share.google/TAFTVpd3DXusV7K7l',
  },
  {
    id: 'commartsw6',
    name: 'Workshop PA',
    description:
      'ผู้เข้าร่วมงานจะได้ลองลงมือทำกิจกรรมที่มีเนื้อหาเกี่ยวกับภาควิชาศิลปะการแสดง รายละเอียดโปรดติดตามเพิ่มเติม',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/nitadecuopenhouse',
    faculty: 'commarts',
    owner: 'ภาควิชาการสื่อสารการเเสดง',
    locationName: 'อาคารมงกุฎสมมติวงศ์',
    locationURL: 'https://share.google/TAFTVpd3DXusV7K7l',
  },
  // คณะพาณิชยศาสตร์และการบัญชี
  {
    id: 'cbsw1',
    name: 'ห้องหลักสูตร',
    description:
      'เป็นพื้นที่กิจกรรมที่แต่ละหลักสูตรจัดเตรียมกิจกรรมเชิงวิชาการแบบเจาะลึก โดยหมุนเวียนไปตามแต่ละหลักสูตร ใช้เวลาประมาณ 1 ชั่วโมง น้อง ๆ จะได้รับประสบการณ์เชิงปฏิบัติการเกี่ยวกับเนื้อหาวิชาเฉพาะทาง ซึ่งรายละเอียดเพิ่มเติมจะนำเสนอในหัวข้อห้องหลักสูตร รวมถึงเชิญศิษย์เก่าที่ประสบความสำเร็จ มาเล่าประสบการณ์ตรงในการทำงาน สถานการณ์ตลาดแรงงาน ทักษะที่จำเป็นในโลกการทำงานปัจจุบัน เพื่อช่วยในการตัดสินใจเลือกสายการศึกษาที่เหมาะสม',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://forms.gle/kjhZ23mANPczkmFY6',
    faculty: 'cbs',
    timeSlot: '8.40 - 10.10 / 10.25 - 11.55 / 12.40 - 14.10 / 14.25 - 15.55',
    locationName: 'อาคารไชยยศสมบัติ',
  },
  {
    id: 'cbsw2',
    name: 'Campus Tour',
    description:
      'กิจกรรม Campus Tour พาผู้เข้าร่วมชมสิ่งอำนวยความสะดวกและห้องปฏิบัติการที่สำคัญ ได้แก่ CBS Lounge ที่เปิดพื้นที่อิสระสำหรับการทำกิจกรรมกลุ่ม และ Financial Laboratory ซึ่งมีเทคโนโลยีและฐานข้อมูลสำหรับงานวิจัยและการวิเคราะห์ทางการเงินชั้นนำระดับโลก เพื่อให้น้อง ๆ ได้เห็นสภาพแวดล้อมการเรียนรู้อย่างแท้จริง',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://forms.gle/GsArkyGEQHhfRJV58',
    faculty: 'cbs',
    timeSlot: '8.40 - 10.10 / 10.25 - 11.55 / 12.40 - 14.10 / 14.25 - 15.55',
    locationName: 'อาคารไชยยศสมบัติ',
  },
  {
    id: 'cbsw3',
    name: 'บูธกลางให้คำแนะนำ',
    description:
      'ห้องแนะแนวกลางเป็นพื้นที่ที่นิสิตจากหลักสูตรต่าง ๆ ได้แก่ หลักสูตรบัญชี หลักสูตรบริหาร หลักสูตรสถิติ และหลักสูตร BBA มาให้คำแนะนำแก่น้อง ๆ โดยตรงเกี่ยวกับการเลือกหลักสูตร แนวทางการเรียน และภาพรวมชีวิตในรั้วมหาวิทยาลัย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://forms.gle/BN2XWEV3Xr2g482M6',
    faculty: 'cbs',
    locationName: 'อาคารไชยยศสมบัติ',
  },
  {
    id: 'cbsw4',
    name: 'one-on-one',
    description:
      'เป็นพื้นที่สำหรับน้อง ๆ ที่มีข้อสงสัยและอยากรู้เพิ่มเติมเกี่ยวกับคณะบัญชีจุฬาได้มาพูดคุยกับพี่แนะแนวจากแต่ละสาขา มาคอยให้คำปรึกษาน้องแบบ 1:1',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://forms.gle/BN2XWEV3Xr2g482M6',
    faculty: 'cbs',
    locationName: 'คณะ',
  },
  {
    id: 'cbsw5',
    name: 'เวทีกลาง',
    description:
      'พื้นที่จัดแสดงความสามารถและศักยภาพของนิสิต ผ่านการแสดงดนตรีสากลและดนตรีไทย เพื่อสร้างแรงบันดาลใจและเพิ่มบรรยากาศแห่งความสนุกสนานตลอดกิจกรรม อีกทัเงยังมีทอล์คโชว์จากรุ่นพีที่กำลังศึกษามาให้ข้อมูลและเล่าประสบการณ์เกี่ยวกับชีวิตในรั้วบัญชีจุฬา',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://forms.gle/BN2XWEV3Xr2g482M6',
    faculty: 'cbs',
    locationName: 'คณะ',
  },
  {
    id: 'cbsw6',
    name: 'workshop',
    description:
      'พื้นที่ที่มุ่งเน้นการจัดกิจกรรมนันทนาการเพื่อเพิ่มความสนุกสนาน สร้างบรรยากาศที่ผ่อนคลายและเป็นกันเอง พร้อมกิจกรรมและของที่ระลึกให้น้อง ๆ ได้รับประสบการณ์และความประทับใจกลับไป',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://forms.gle/BN2XWEV3Xr2g482M6',
    faculty: 'cbs',
    locationName: 'คณะ',
  },
  {
    id: 'cbsw7',
    name: 'Sife MasterClass',
    description:
      'SIFE Master Class เป็นกิจกรรมที่เน้นการลงมือปฏิบัติจริงเกี่ยวกับธุรกิจเพื่อสังคมผ่านการเรียนรู้แบบ Activity-based Learning ผู้เข้าร่วมจะได้ฝึกทักษะการเป็นที่ปรึกษาธุรกิจ การวางกลยุทธ์ และการทำงานเป็นทีม เพื่อแก้ไขปัญหาธุรกิจอย่างเป็นรูปธรรม พร้อมรับประกาศนียบัตรจากคณะพาณิชยศาสตร์และการบัญชี',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cbs.openhouse',
    faculty: 'cbs',
    locationName: 'อาคาร 50 ปี',
  },
  {
    id: 'cbsw8',
    name: 'CBS Brunch & Buddy',
    description:
      '“อยากรู้จัก CBS ต้องคุยกับที่สุดของ CBS” CBS Brunch & Buddy จะพาทุกคนไปค้นหาคำตอบ “Why CBS?” เพราะชีวิตในมหาวิทยาลัย “ไม่ใช่เพียงแต่เลือกคณะที่ชอบ แต่ต้องเป็นคณะที่ใช่” ผ่าน Life-Changing Conversation บนโต๊ะอาหารกับรุ่นพี่คณะบัญชี จุฬาฯ และเพื่อนต่างโรงเรียนแบบสุด Exclusive เกี่ยวกับเรื่องราวและประสบการณ์จากคณะบัญชีในด้าน การเรียน กิจกรรม และการทำงาน ของรุ่นพี่มากกว่า 20 คน จากทุกภาควิชา)',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cbs.openhouse',
    faculty: 'cbs',
    locationName: 'อาคารไชยยศสมบัติ',
  },
  // คณะแพทย์ศาสตร์

  // คณะเภสัชศาสตร์
  {
    id: 'pharmw1',
    name: 'ฐานแนะแนวการเรียน',
    description:
      'ฐานแนะแนวการเรียนของเราพร้อมให้คำแนะนำและตอบคำถามน้อง ๆ ทุกคนตั้งแต่หลักสูตร การเตรียมตัวสอบเข้า การเรียนและสังคมภายในคณะจากประสบการณ์ตรงของรุ่นพี่ตัวจริง กิจกรรมสุด EXCLUSIVE แบบนี้ จะพลาดไม่ได้แล้วนะ!',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 12:00 / 12:30 - 16:15',
    locationName: 'ใต้อาคาร 80 ปี หน้าโรงอาหาร ',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw2',
    name: 'การแนะแนววิชาชีพ',
    description:
      'เภสัชที่ไม่ได้อยู่แค่ในร้านยา และบทบาทในยุคเอไอเฟื่องฟู พบกับวิทยากรสุด exclusive ที่จะเปิดมุมมองชาวเภสัชในทุก ๆ ด้าน กับการบรรยายหัวข้อ “บทบาทของเภสัชกรในยุคโลกาภิวัตน์” พิเศษสุด ๆ ในช่วงถาม-ตอบ ที่พร้อมตอบคำถามที่ทุกคนอยากรู้จากผู้เชี่ยวชาญที่หาจากที่ไหนไม่ได้!!!',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '9:00 - 11:00 / 13:00 - 15:00',
    locationName: 'อาคาร 80 ปี ห้อง 702',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw3',
    name: 'ฐานวิชาการ Manufacturing',
    description:
      'เภสัชกรสายการผลิตคืออะไร? ต้องมามุงกันที่ฐาน MANUFACTURING! เราสามารถควบคุมเครื่องจักรและเครื่องมือที่หลากหลาย เรียนรู้ตั้งแต่เริ่มว่ายาเม็ด เกิดขึ้นมาได้อย่างไร รวมถึงขั้นตอนการทดสอบคุณภาพยา และได้ลองใช้เครื่องมือที่ใช้อุตสาหกรรมจริง',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot:
      '8:15-9:00 / 9:15-10:00 / 10:15-11:00 / 11:15-11:45 / 12:45-13:30 / 13:45-14:30 / 14:45-15:30 / 15:45-16:15',
    locationName: 'อาคารเภสัชศาสตร์ ห้องตอกเม็ดยา',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw4',
    name: 'ฐานวิชาการ Medical Chemistry',
    description:
      "MED CHEM ไม่ได้มีดีแค่หลอดทดลอง แต่ยังมี 'เครื่องมือวิเคราะห์สุดไฮเทค' มาโชว์น้อง ๆ อีกด้วย!  มาดูกันว่า QC ยาเขาทำกันยังไง มาเจอกันได้ที่ฐาน MED CHEM เลยจ้า!",
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'อาคาร 80 ปี ห้อง 301',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw5',
    name: 'ฐานวิชาการ Pharmaceutics',
    description:
      'มาเปิดเบื้องหลังอีกมิติของยา ที่ฐาน PHARMACEUTICS มารู้จักกับยารูปแบบอื่น ๆ ที่ไม่ได้มีแค่ยาเม็ดหรือแคปซูล พร้อมเชื่อมโยงความรู้จากยาไปสู่ผลิตภัณฑ์ดูแลผิวที่ใช้ในชีวิตประจำวัน ใครอยากรู้ว่าออกแบบและพัฒนากันยังไง ฐาน PHARMACEUTICS ห้ามพลาด!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'อาคาร 80 ปี ห้อง 303',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw6',
    name: 'ฐานวิชาการ Pharmacognosy',
    description:
      'ฐาน PHARMACOGNOSY จะพาน้อง ๆ ไปดู "สมุนไพร" ผ่านการทัวร์ MUSEUM  มาหาคำตอบกันว่า จากใบไม้หนึ่งใบกลายมาเป็นยาช่วยชีวิตคนได้ยังไง? ฐานนี้มีคำตอบ!',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot:
      '8:15-8:45 / 8:50-9:20 / 9:25-9:55 / 10:00-10:30 / 10:35-11:05 / 11:10-11:40 / 12:45-13:15 / 13:20-13:50 / 13:55-14:25 / 14:30-15:00 / 15:05-15:35 / 15:40-16:10',
    locationName: 'พิพิธภัณฑ์สมุนไพร ชั้น 3 โอสถศาลา',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw7',
    name: 'ฐานวิชาการ Drug Discovery & Development (DDD)',
    description:
      'เคยสงสัยไหมว่า ยารู้ได้ไงว่าต้องวิ่งไปรักษาตรงไหน? แล้วระหว่างการเดินทางยาจะต้องเจออะไรในร่างกายบ้าง? ฐาน DRUG DISCOVERY & DEVELOPMENT จะพาน้อง ๆ ไปสนุกกับ 2 MISSION ภายในฐาน ห้ามพลาด!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 401',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw8',
    name: 'ฐานวิชาการ Social and Administrative Pharmacy (SAP)',
    description:
      'อยากรู้ไหมว่าเภสัชกรมีบทบาทใน “ระบบสุขภาพทั้งประเทศ” อย่างไร ฐานนี้จะพาไปรู้จักเส้นทางอาชีพที่อยู่เบื้องหลังความปลอดภัยของประชาชน ไม่ว่าจะเป็นงานคุ้มครองผู้บริโภคด้านยา งานส่งเสริมสุขภาวะ ไปจนถึง ผู้ดูแลการขออนุมัติและขึ้นทะเบียนผลิตภัณฑ์สุขภาพ มาค้นพบว่าเภสัชกรสามารถขับเคลื่อนระบบสุขภาพได้มากกว่าที่คิด!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 503',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw9',
    name: 'ฐานวิชาการ เภสัชกรรมร้านยา',
    description:
      'มาลองเป็นเภสัชกรร้านยาตัวจริง เรียนรู้บทบาทการจัดเตรียมยาให้ผู้ป่วย ฝึกนับเม็ดยาด้วยถาดนับยา และทดลองเขียนฉลากยาแบบเภสัชกรตัวน้อย ให้ถูกต้อง ครบถ้วน และปลอดภัย แล้วจะเข้าใจว่าทุกขั้นตอนเล็ก ๆ ล้วนส่งผลต่อความปลอดภัยของคนไข้',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 402',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw10',
    name: 'ฐานวิชาการ เภสัชกรรมชุมชน',
    description:
      'มาลองเป็นเภสัชกรร้านยาตัวจริง เรียนรู้บทบาทการจัดเตรียมยาให้ผู้ป่วย ฝึกนับเม็ดยาด้วยถาดนับยา และทดลองเขียนฉลากยาแบบเภสัชกรตัวน้อย ให้ถูกต้อง ครบถ้วน และปลอดภัย แล้วจะเข้าใจว่าทุกขั้นตอนเล็ก ๆ ล้วนส่งผลต่อความปลอดภัยของคนไข้',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 402',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw11',
    name: 'ฐานวิชาการ เภสัชกรรมโรงพยาบาล',
    description:
      'เภสัชกรในโรงพยาบาลมีหน้าที่แค่จ่ายยาเท่านั้นไหมนะ? มารู้จักหลักการสื่อสาร ISBAR ผ่านสถานการณ์จำลองและกิจกรรมภายในฐาน พร้อมโอกาสสวมบทบาทเป็นเภสัชกรตัวน้อยในทีมรักษา ที่ฐานเภสัชกรโรงพยาบาล!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 402',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw12',
    name: 'ฐานวิชาการ Pharmaceutical Microbiology',
    description:
      'กว่ายาจะถึงมือคนไข้ ต้องผ่าน “ด่านจุลชีวะ” ก่อนเสมอ! เพราะโลกของเภสัชฯ ไม่ได้มีแค่เม็ดยา แต่ยังมีโลกของจุลินทรีย์ที่มองไม่เห็น  อยากรู้ไหมว่าจุลชีวะเกี่ยวข้องกับงานเภสัชยังไง? มาเจอกันที่ฐาน Microbiology ได้เลย!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 501',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },
  {
    id: 'pharmw13',
    name: 'ฐานวิชาการ Pharmaceutical Nutrition',
    description:
      'ใครบอกว่าเภสัชมีแต่เรื่องยา? เรื่อง “กิน” ก็สำคัญไม่แพ้กันนะ! มารู้จักโลกของโภชนาการในมุมเภสัชกร กับกิจกรรมสนุก ๆ ที่ได้ทั้งความรู้และความมันส์  อยากอัปสกิลเรื่องปากท้องแบบโปร ๆ มาเจอกันที่ฐาน Nutrition เลย!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rxcu_openhouse',
    faculty: 'pharm',
    timeSlot: '8:15 - 9:55 / 10:05 - 11:45 / 12:45 - 14:25 / 14:35 - 16:15',
    locationName: 'ตึก 80 ปี ห้อง 502',
    locationURL: 'https://maps.app.goo.gl/NafCdUmNp18ACybb7',
  },

  // คณะรัฐศาสตร์
  {
    id: 'polsciw1',
    name: 'Polsci Café ☕',
    description:
      "กิจกรรม 'ห้องปรึกษาทั่วไป' เป็นกิจกรรมให้คำแนะนำด้านการศึกษาที่จัดเป็นรอบ ๆ เพื่อเปิดโอกาสให้น้อง ๆ ได้ทำความรู้จักคณะรัฐศาสตร์ในภาพรวม โดยจะมีการแนะนำโครงสร้างและลักษณะการเรียนของแต่ละภาควิชาในเบื้องต้น ก่อนจะแยกการพูดคุยตามภาควิชาอย่างใกล้ชิด กิจกรรมจัดรอบละ 40 คน แบ่งเป็น 2 ห้อง ตลอดระยะเวลา 2 วัน คือวันเสาร์และวันอาทิตย์ ภายในกิจกรรม น้อง ๆ จะได้พูดคุยกับพี่ ๆ ตัวแทนจากแต่ละภาควิชาในรูปแบบวงสนทนา โดยมีการเวียนพูดคุยทั้งหมด 2 รอบ น้องสามารถเลือกอยู่พูดคุยกับภาควิชาเดิมเพื่อสอบถามข้อมูลเชิงลึกเพิ่มเติม หรือเลือกเปลี่ยนภาควิชาเพื่อรับฟังมุมมองและข้อมูลที่หลากหลายมากขึ้นตามความสนใจ กิจกรรมนี้เหมาะสำหรับน้อง ๆ ที่ยังไม่รู้จักคณะรัฐศาสตร์มากนัก หรือผู้ที่สนใจเข้าศึกษาในคณะ แต่ต้องการทำความเข้าใจภาพรวมของแต่ละภาควิชาก่อนตัดสินใจเลือกแนวทางการเรียนในอนาคต",
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://docs.google.com/forms/d/e/1FAIpQLSdICBgxJ_kYVQiQui5SncdKsYWLG6nm78J1bCxhGjkneAI59A/viewform?usp=publish-editor',
    faculty: 'polsci',
    timeSlot: '13:00 - 13.45 / 14.00 - 14.45 / 15.00 - 15.45',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) ห้อง 607-608',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  {
    id: 'polsciw2',
    name: 'Polsci Lounge 🛋️',
    description:
      "กิจกรรม 'ห้องปรึกษาเชิงลึก' เป็นกิจกรรมให้คำแนะนำแบบตัวต่อตัวระหว่างน้อง ๆ กับรุ่นพี่ เพื่อเปิดพื้นที่สำหรับการพูดคุยในประเด็นที่มีความเฉพาะเจาะจงและลงรายละเอียดมากยิ่งขึ้น กิจกรรมนี้เหมาะสำหรับน้อง ๆ ที่มีพื้นฐานความรู้เกี่ยวกับคณะรัฐศาสตร์ในระดับหนึ่งแล้ว และต้องการสอบถามข้อมูลเชิงลึกเกี่ยวกับเนื้อหาการเรียน แนวทางการศึกษา หรือประสบการณ์ในแต่ละภาคสาขาวิชา ภายในห้องจะมีพี่ ๆ จากแต่ละภาคสาขาวิชาที่มีความรู้และประสบการณ์ตรงคอยให้คำปรึกษา โดยน้องสามารถเลือกพูดคุยในประเด็นที่ตนเองสนใจ ไม่ว่าจะเป็นรายละเอียดของหลักสูตร การเรียนในแต่ละชั้นปี แนวทางการทำงานในอนาคต หรือข้อสงสัยเฉพาะด้านอื่น ๆ นอกจากนี้ ห้องปรึกษาเชิงลึกยังเหมาะสำหรับน้อง ๆ ที่มีความตั้งใจจะเข้าศึกษาต่อในคณะรัฐศาสตร์ แต่ยังลังเลหรือไม่แน่ใจว่าควรเลือกภาคสาขาวิชาใด โดยจะมีพี่ ๆ คอยให้คำแนะนำแบบตัวต่อตัว เพื่อช่วยให้น้องสามารถประเมินความสนใจและตัดสินใจเลือกแนวทางการเรียนที่เหมาะสมกับตนเองมากที่สุด",
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/polscicu.oph',
    faculty: 'polsci',
    timeSlot: '13:00 - 16:00',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) ห้อง 614',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  {
    id: 'polsciw3',
    name: 'SD Career Talks (เวทีพูดคุยเส้นทางอาชีพกับศิษย์เก่าสิงห์ดำ)',
    description:
      'กิจกรรม "เสวนาเส้นทางอาชีพ" เป็นกิจกรรมที่พี่ ๆ ศิษย์เก่าจะมาร่วมแบ่งปันประสบการณ์ตั้งแต่ในช่วงที่ยังเป็นนิสิต รวมไปถึงการแนะนำในพาร์ทของการทำงาน และความเป็นรัฐศาสตร์สามารถนำไปปรับใช้กับการทำงานได้อย่างไรบ้าง ซึ่งจะช่วยให้ผู้เข้าร่วมมองเห็นเส้นทางอาชีพของผู้ที่จบการศึกษาจากคณะรัฐศาสตร์ได้ชัดเจนมากขึ้น',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/polscicu.oph',
    faculty: 'polsci',
    timeSlot: '10.00 - 12.30',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) Singhdam Space',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  {
    id: 'polsciw4',
    name: 'Talking with Insiders (PGS)',
    description:
      'กิจกรรม "ห้องแนะแนวหลักสูตร PGS" เป็นกิจกรรรมที่เปิดโอกาสให้น้อง ๆ ที่สนใจในคณะรัฐศาสตร์หลักสูตรนานาชาติได้เข้าถึงข้อมูลของหลักสูตรมากยิ่งขึ้น และช่วยให้น้องๆ มีความเข้าใจเกี่ยวกับหลักสูตร PGS อย่างลึกซึ้ง นอกจากนี้ กิจกรรมดังกล่าวยังช่วยแนะแนวเส้นทางการประกอบอาชีพในอนาคตของน้อง ๆ ไม่ว่าจะเป็น 1) นักการทูต 2) นักวิจัย หรือ 3) ต่อยอดธุรกิจครอบครัว (อย่างไรก็ตาม ขนาดของกลุ่มตัวอย่างยังคงมีจำนวนจำกัด เนื่องจากหลักสูตรนี้เพิ่งเปิดดำเนินการได้ไม่นาน)',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/polscicu.oph',
    faculty: 'polsci',
    timeSlot: '10.00 - 12.30 / 13.00 - 16.00',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) ห้อง 614',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  {
    id: 'polsciw5',
    name: 'กิจกรรมการแข่งขันตอบปัญหาวิชาการรัฐศาสตร์',
    description:
      'กิจกรรม "การแข่งขันตอบปัญหาวิชาการรัฐศาสตร์ ครั้งที่ 9" เป็นกิจกรรมการแข่งขันทางวิชาการที่เปิดโอกาสให้นักเรียนระดับมัธยมศึกษาตอนปลายได้มาลองวัดประชันความรู้ด้านสังคมศึกษาและรัฐศาสตร์ พร้อมชิงของรางวัลมากมาย',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/polscicu.oph',
    faculty: 'polsci',
    timeSlot: '08:00 - 17:00',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) ห้อง 507-508 และ 1308',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  {
    id: 'polsciw6',
    name: 'Mock Classroom (PGS)',
    description:
      'กิจกรรมห้องเรียนจำลองเป็นการเปิดห้องเรียนจำลองให้ผู้เข้าร่วมงานได้สัมผัสบรรยากาศการเรียนการสอนเสมือนจริงในหลักสูตรการเมืองและโลกสัมพันธ์ คณะรัฐศาสตร์',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/polscicu.oph',
    faculty: 'polsci',
    timeSlot: '13:00 - 14:30',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) ห้อง 609',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  {
    id: 'polsciw7',
    name: 'กิจกรรมห้องเรียนจำลอง (Classroom Simulation)',
    description:
      'กิจกรรมห้องเรียนจำลองเป็นการเปิดห้องเรียนจำลองให้ผู้เข้าร่วมงานได้สัมผัสบรรยากาศการเรียนการสอนเสมือนจริงในหลักสูตรภาคปกติของคณะรัฐศาสตร์ทั้งสี่ภาควิชา ได้แก่ ภาควิชาการปกครอง (Government) ภาควิชาความสัมพันธ์ระหว่างประเทศ  (International Relations) ภาควิชารัฐประศาสนศาสตร์ (Public Administration) และภาควิชาสังคมวิทยาและมานุษยวิทยา (Sociology and Anthropology)',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://docs.google.com/forms/d/e/1FAIpQLSe4t5Ub9uM4EoCzeYCTn7Hh-WpFdZc6zUdnX3T0Cr_TF5fC8A/viewform?usp=publish-editor',
    faculty: 'polsci',
    timeSlot: '09.00 - 12.30',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี) ห้อง M08',
    locationURL: 'https://maps.app.goo.gl/aUsm2S7Y8ap1woXY9',
  },
  {
    id: 'polsciw8',
    name: 'กิจกรรมการแข่งขันโต้วาทีระดับชั้นมัธยมศึกษาตอนปลาย',
    description:
      'กิจกรรมแข่งขันโต้วาทีในระดับชั้นมัธยมศึกษาตอนปลาย เพื่อแสดงทรรศนะและพัฒนาทักษะด้านการพูด ผ่านมิติของรัฐศาสตร์',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/polscicu.oph',
    faculty: 'polsci',
    timeSlot: '8.30-15.00',
    locationName: 'อาคารเกษม อุทยานิน (รัฐศาสตร์ 60 ปี)',
    locationURL: 'https://maps.app.goo.gl/7bC9QwXTxRhomXvE9',
  },
  // คณะวิทยาศาสตร์
  {
    id: 'sciw1',
    name: 'นิทรรศการภาควิชา นิทรรศการกลาง และบูธ TCAS',
    description:
      'นิทรรศการให้ข้อมูลการเรียนและเส้นทางอาชีพในอนาคตของภาควิชาและหลักสูตรนานาชาติ รวม 18 บูธ พร้อมบูธกลางและบูธแนะแนว TCAS สำหรับนักเรียนที่สนใจเข้าศึกษาในคณะวิทยาศาสตร์',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    locationName: 'บริเวณใต้อาคารมหามกุุฏ',
    locationURL: 'https://maps.app.goo.gl/cN23XxNUfm7QKn6M9',
  },
  {
    id: 'sciw2',
    name: 'Workshop ภาควิชาคณิตศาสตร์และวิทยาการคอมพิวเตอร์',
    description: 'กิจกรรม workshop : Secret Code',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาคณิตศาสตร์และวิทยาการคอมพิวเตอร์',
    locationName: 'อาคารมหาวชิรุณหิศ',
    locationURL: 'https://maps.app.goo.gl/yESKbs1e7ueKnxx9A',
  },
  {
    id: 'sciw3',
    name: 'Workshop ภาควิชาเคมีเทคนิค',
    description:
      'กิจกรรมเปิดโลกที่ห้องปฏิบัติการชั้นใต้ดิน (Unit Lab) ชมชุดทดลองจริงทั้งท่อ ปั๊ม วาล์ว ระบบการไหล การถ่ายเทความร้อน และการแยกสาร พร้อมคำอธิบายเข้าใจง่าย ให้เห็นภาพการเรียนของภาควิชาอย่างชัดเจน',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาเคมีเทคนิค',
    locationName: 'อาคารมหามกุฏ ชั้นใต้ดิน',
    locationURL: 'https://maps.app.goo.gl/cN23XxNUfm7QKn6M9',
  },
  {
    id: 'sciw4',
    name: 'Workshop ภาควิชาธรณีวิทยา',
    description:
      'กิจกรรม workshop : การคัดตะกอน และผู้เข้าร่วมจะได้ออกแบบ size chart ของตนเอง',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาธรณีวิทยา',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw5',
    name: 'Workshop ภาควิชาวิทยาศาสตร์สิ่งแวดล้อม',
    description: 'กิจกรรม workshop : วัดต้นไม้และคำนวณคาร์บอน',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาวิทยาศาสตร์สิ่งแวดล้อม',
    locationName: 'บริเวณอาคารวิทยาศาสตร์ทั่วไป (อาคารวิทยาศาสตร์สิ่งแวดล้อม)',
    locationURL: 'https://maps.app.goo.gl/LRXQiwwKwXAPA3UX7',
  },
  {
    id: 'sciw6',
    name: 'Workshop ภาควิชาชีวเคมี',
    description: 'กิจกรรม workshop : การสกัด DNA จากกล้วย',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาชีวเคมี',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw7',
    name: 'Workshop ภาควิชาวัสดุศาสตร์',
    description:
      'ภายในพื้นที่ SCI SPACE : Workshop ทำสไลม์แม่เหล็กและหล่อปูนปลาสเตอร์ และบริเวณตึกวัสดุศาสตร์ : Workshop throwing+PU Foam+processing',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาวัสดุศาสตร์',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space และตึกวัสดุศาสตร์',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw8',
    name: 'Workshop ภาควิชาจุลชีววิทยา',
    description: 'กิจกรรม workshop : Streak and Pour',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาจุลชีววิทยา',
    locationName: 'อาคารมหาวชิรุณหิศ',
    locationURL: 'https://maps.app.goo.gl/yESKbs1e7ueKnxx9A',
  },
  {
    id: 'sciw9',
    name: 'Workshop ภาควิชาเทคโนโลยีทางภาพและการพิมพ์',
    description:
      'Munsell 100 Hue Test :การแข่งขันการแยกแยะสี โดยให้ผู้ทดสอบจัดเรียงแถบสีที่มีเฉดสีใกล้เคียงกัน 85 แถบใน 4 แถว ตามลำดับสีธรรมชาติ เพื่อประเมินความแม่นยำในการมองเห็นสีและตรวจหาภาวะบกพร่องทางการมองเห็นสี',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาเทคโนโลยีทางภาพและการพิมพ์',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw10',
    name: 'Workshop ภาควิชาเทคโนโลยีทางอาหาร',
    description: 'กิจกรรม workshop : ตะลุยวิทยาศาสตร์อาหาร',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาเทคโนโลยีทางอาหาร',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw11',
    name: 'Workshop ภาควิชาเคมีและหลักสูตรเคมีประยุกต์ (BSAC)',
    description: 'กิจกรรม workshop : การทำน้ำหอม',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'ภาควิชาเคมีและหลักสูตรเคมีประยุกต์ (BSAC)',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw12',
    name: 'Workshop หลักสูตรเทคโนโลยีชีวภาพ (BBTech)',
    description: 'กิจกรรม workshop : ไขปริศนาด้วย STR',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'หลักสูตรเทคโนโลยีชีวภาพ (BBTech)',
    locationName: 'อาคารแถบนีละนิธิ ในพื้นที่ Sci Space',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw13',
    name: 'Workshop หลักสูตรวิทยาศาสตร์และเทคโนโลยีอุตสาหการ (BISTECH)',
    description: 'กิจกรรม workshop : F1 Car Race',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scichulaopenhouse',
    faculty: 'sci',
    owner: 'หลักสูตรวิทยาศาสตร์และเทคโนโลยีอุตสาหการ (BISTECH)',
    locationName: 'SIS Lounge อาคารแถบ นีละนิธิ',
    locationURL: 'https://maps.app.goo.gl/hgfFDT8zsBWPLEvc8',
  },
  {
    id: 'sciw14',
    name: 'โครงการการแข่งขันตอบปัญหาวิทยาศาสตร์ SCiLYMPIC',
    description:
      'กิจกรรม SCiLYMPIC เป็นการแข่งขันวิชาการด้านวิทยาศาสตร์และคณิตศาสตร์ สำหรับนักเรียนระดับมัธยมศึกษา ครอบคลุมทั้งภาคทฤษฎีและภาคปฏิบัติ มุ่งพัฒนาทักษะการคิดวิเคราะห์ การแก้ปัญหา และการประยุกต์ความรู้ในสถานการณ์ต่าง ๆ',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/scilympic_official',
    faculty: 'sci',
    timeSlot: '8:00 - 18:00',
    locationName: 'อาคารมหามกุฏ',
    locationURL: 'https://maps.app.goo.gl/cN23XxNUfm7QKn6M9',
  },
  // คณะวิทยาศาสตร์การกีฬา

  // คณะวิศวกรรมศาสตร์
  {
    id: 'engw1',
    name: 'โซน Booth ภาควิชา',
    description:
      'กิจกรรม ให้แต่ละภาควิชามา present ในรูปของบูธกิจกรรม ให้น้อง ๆ เข้ามาสอบถาม',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
    locationName: 'ลาน intania',
    locationURL: 'https://maps.app.goo.gl/tCxBd5GxDi3QvL6B8',
  },
  {
    id: 'engw2',
    name: 'โซน Booth ชมรม',
    description:
      'กิจกรรม ให้แต่ละชมรมมา present ในรูปของบูธกิจกรรม ให้น้อง ๆ เข้ามาสอบถาม',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
    locationName: 'บริเวณถนน หน้าอาคารวิศวกรรม 1 และ 2',
  },
  {
    id: 'engw3',
    name: 'Workshop ภาควิชา',
    description:
      'กิจกรรมให้แต่ละภาค workshop ให้ผู้เข้าร่วมมีส่วนร่วมได้ โดยแต่ละภาคจะมีกิจกรรม ที่แตกต่างออกไปในสายนั้น ๆ',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
    timeSlot:
      '9:00 - 10:00 / 10:15 - 11:15 / 11:30 - 12:30 / 13:15 - 14:15 / 14:30 - 15:30',
  },
  {
    id: 'engw4',
    name: 'โซน Workshop innovation ของคณะ และทางอาจารย์',
    description: 'มีการนำ innovation มาให้น้องๆรับชม และลงมือ workshop',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
  },
  {
    id: 'engw5',
    name: 'เวทีกลางจัดแสดง',
    description: 'มีการแสดงของชมรมและกิจกรรมทั่วไป ในการประชาสัมพันธื',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
  },
  {
    id: 'engw6',
    name: 'กิจกรรมแนะแนวภายในหอประชุม Hall of intania',
    description:
      'เป็นกิจกรรมทีจะนำ รุ่นพี่ คณะอาจารย์มาพูดถึง คณะวิศวะ ภายในหอประชุม',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
    locationName: 'หอประชุม Hall of intania',
    locationURL: 'https://maps.app.goo.gl/75v8d4iGP2DQHBKX9',
  },
  {
    id: 'engw7',
    name: 'การแข่งขันตอบปัญหาคณิตศาสตร์เชิงวิศวกรรม (Integation Bee challenge)',
    description:
      'กิจกรรม แข่งขัน อินทิเกรตเชิงคณิตศาสตร์ ผู้เข้าร่วมเป็นน้อง ๆ มปลาย ',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
    locationName: 'หอประชุมอาคาร 4 ชั้น 2',
    locationURL: 'https://maps.app.goo.gl/bsZ6nesbJcqWXbHt8',
  },
  {
    id: 'engw8',
    name: 'โซนจัดแสดงนวัตกรรมที่เกี่ยวข้องกับวิศวกรรม',
    description: 'มีการนำ innovation มาให้น้องๆรับชม',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/cuintaniaopenhouse',
    faculty: 'eng',
  },
  // คณะศิลปกรรมศาสตร์
  {
    id: 'faaw1',
    name: 'เวทีกลาง',
    description:
      'ตั้งเวทียกสูงสำหรับจัดแสดงความสามารถของนิสิตคณะศิลปกรรมศาสตร์',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/smo.singum',
    faculty: 'faa',
    timeSlot: '09.00-15.00',
    locationName: 'บริเวณหน้าอาคารศิลปกรรมศาสตร์',
  },
  {
    id: 'faaw2',
    name: 'นิทรรศการ',
    description:
      'จัดแสดงตัวอย่างผลงาน ข้อมูลคณะ รวมถึงรายละเอียดเกี่ยวกับแต่ละภาควิชาสำหรับผู้ที่สนใจ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/smo.singum',
    faculty: 'faa',
    timeSlot: '09.00-15.00',
    locationName: 'บริเวณหน้าอาคารศิลปกรรมศาสตร์',
  },
  {
    id: 'faaw3',
    name: 'พื้นที่ ถาม-ตอบ',
    description:
      'พื้นที่สำหรับให้น้อง ๆ ที่สนใจคณะศิลปกรรมศาสตร์เข้ามาแลกเปลี่ยน สอบถามข้อมูลจากรุ่นพี่ในคณะ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/smo.singum',
    faculty: 'faa',
    timeSlot: '09.00-15.00',
    locationName: 'ห้องฟ้าใหม่ อาคารศิลปกรรมศาสตร์',
  },
  // คณะเศรษฐศาสตร์
  {
    id: 'econ1',
    name: 'Exhibition',
    description:
      'จัดนิทรรศการให้ความรู้เบื้องต้นเกี่ยวกับการเรียนในสาขาเศรษฐศาสตร์ โดยเนื้อหาครอบคลุมการอธิบายหลักสูตรที่คณะเศรษฐศาสตร์มี สายการทำงานเบื้องต้น วิธีการรับเข้า รวมไปถึงมีการจัดกิจกรรมเกมที่มีการประยุกต์เนื้อหาทางเศรษฐศาสตร์เพื่อให้ผู้เข้าชมมีความเข้าใจในหลักวิธีคิดทางเศรษฐศาสตร์มากขึ้น',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/econlab_cu',
    faculty: 'econ',
    timeSlot: '09:00 - 12:00 / 13:00 - 16:00',
    locationName: 'บริเวณโถงใต้อาคารคณะเศรษฐศาสตร์',
  },
  {
    id: 'econ2',
    name: 'รุ่นพี่ Talk',
    description:
      'จัดกิจกรรมให้ผู้เข้าร่วมได้มีโอกาสพูดคุย ปรึกษา และสอบถามข้อมูลเบื้องต้นเกี่ยวกับการเข้าเรียนในสาขาเศรษฐศาสตร์ รวมไปถึงประสบการณ์ และบรรยากาศในการเรียนจากรุ่นพี่นิสิตคณะเศรษฐศาสตร์โดยตรง',
    hasPreregistered: false,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/econlab_cu',
    faculty: 'econ',
    timeSlot:
      '28 March: 09:00 - 12:00 / 28 March: 13:00 - 13:30 / 28 March: 15:30 - 16:00 / 29 March: 09:00 - 12:00 / 29 March: 13:00 - 16:00',
    locationName: 'ห้องสมุด คณะเศรษฐศาสตร์',
  },
  {
    id: 'econ3',
    name: 'ศิษย์เก่า Talk',
    description:
      'จัดกิจกรรมเสวนา โดยศิษย์เก่าจากคณะเศรษฐศาสตร์ 3 ท่าน มาร่วมเสวนาเกี่ยวประสบการณ์ชีวิตในตอนเป็นนิสิตและตอนทำงาน โดยเป็นการแลกเปลี่ยนมุมมองและประสบการณ์ในการทำงานหลังจบการศึกษาจากคณะเศรษฐศาสตร์ในสายงานที่หลากหลายในยุคปัจจุบัน เพื่อเป็นการให้ความรู้ และแนะแนวทางแก่ผู้เข้าร่วม',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/econlab_cu',
    faculty: 'econ',
    timeSlot: '28 March: 14:00 - 15:30',
    locationName: 'ห้องสมุด คณะเศรษฐศาสตร์',
  },
  {
    id: 'econ4',
    name: 'เปิดทรรศน์คณะเศรษฐศาสตร์',
    description:
      'จัดกิจกรรมเปิดทรรศน์ของชมรมต่างๆในคณะเศรษฐศาสตร์ อาทิ ชมรมโต้วาที ชมรมยิงปืน ฯลฯ แต่ละชมรมจะมีการจัดกิจรรมเพื่อให้ผู้เข้าร่วมงานได้มีโอกาสเปิดมุมมองต่อคณะ ได้สัมผัสกับกรรมนอกเหนือจากการเรียนที่หลายหลาย',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/econlab_cu',
    faculty: 'econ',
    timeSlot: '09:00 - 12:00 / 13:00 - 16:00',
    locationName: 'บริเวณโถงใต้อาคารคณะเศรษฐศาสตร์',
  },
  {
    id: 'econ5',
    name: 'ห้องเรียนจำลอง',
    description:
      'จัดการจำลองการเรียนในคณะเศรษฐศาสตร์ เพื่อให้ผู้เข้าร่วมกิจกรรมได้รับความรู้และมีความเข้าใจในพื้นฐานหลักวิธีคิดทางเศรษฐศาสตร์มากยิ่งขึ้น รวมถึงเป็นการได้ลองสัมผัสบรรยากาศการเรียนการสอนในคณะเศรษฐศาสตร์',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/econlab_cu',
    faculty: 'econ',
    timeSlot: '29 March: 09:00 - 09:45 / 29 March: 10:15 - 11:00',
    locationName: 'อาคารคณะเศรษฐศาสตร์ ห้อง 209',
  },

  // คณะสถาปัตยกรรมศาสตร์
  {
    id: 'archw1',
    name: 'Talk Session โดยอาจารย์',
    description:
      'การบรรยายเกี่ยวกับหลักสูตรการเรียนการสอน  การรับสมัคร career path บรรยากาศในการเรียนของแต่ละภาควิชา จำนวน 8 ภาควิชา ภาคละ 30 นาที โดยวันที่ 28 มีนาคม บรรยายโดยอาจารย์ วันที่ 29 มีนาคม บรรยายโดยรุ่นพี่',
    hasPreregistered: true,
    hasLimitParticipants: false,
    url: 'https://forms.gle/75GqSheDABvK35UL8',
    faculty: 'arch',
    timeSlot:
      '10.00 - 10.30 ภาควิชา สถาปัตยกรรมศาสตร์ สาขา สถาปัตยกรรม (AR) / 10.45 - 11.15 ภาควิชา สถาปัตยกรรมศาสตร์ สาขา สถาปัตยกรรมไทย (TR) / 11.30 - 12.00 ภาควิชา สถาปัตยกรรมศาสตร์ภายใน (IA) / 13.00 - 13.30 ภาควิชา ภูมิสถาปัตยกรรม (LA) / 13.45 - 14.15 ภาควิชา การวางแผนภาคและเมือง (UA) / 14.30 - 15.00 ภาควิชา การออกแบบอุตสาหกรรม (ID) / 15.15 - 15.45 หลักสูตร การออกแบบสถาปัตยกรรม นานาชาติ (INDA) / 16.00 - 16.30 หลักสูตร การออกแบบนิเทศศิลป์ นานาชาติ (CommDe)',
    locationName: 'ห้องสมุด ชั้นออดิทอเรียม คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw2',
    name: 'Talk Session โดยรุ่นพี่',
    description:
      'การบรรยายเกี่ยวกับหลักสูตรการเรียนการสอน  การรับสมัคร career path บรรยากาศในการเรียนของแต่ละภาควิชา จำนวน 8 ภาควิชา ภาคละ 30 นาที โดยวันที่ 28 มีนาคม บรรยายโดยอาจารย์ วันที่ 29 มีนาคม บรรยายโดยรุ่นพี่',
    hasPreregistered: true,
    hasLimitParticipants: false,
    url: 'https://forms.gle/75GqSheDABvK35UL8',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'ห้องสมุด ชั้นออดิทอเรียม คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw3',
    name: 'จัดแสดงโมเดล เพลต ประจำแต่ละภาควิชา',
    description:
      'ผลงานแต่ละภาควิชา มีโดล เพลตทีสิส และสามารถปรึกษากับพี่ในภาคได้โดยตรง',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'ห้องสมุดชั้น 2-3 คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw4',
    name: 'ฐานที่ 1 stereotypes',
    description:
      'Stereotypes สไตล์แบบไหนจะใช่เรา ภาพจำของแต่ละภาควิชา ไม่ว่าจะเป็นเนื้อหา หลักสูตร ลักษณะผู้เรียน มาใช้ในการนิยามความเข้าใจเพื่อให้ผู้ที่สนใจได้เข้าใจและเห็นภาพความแตกต่างของแต่ละภาควิชา',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'ถ้ำเสือ หลังโต๊ะลงทะเบียน คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw5',
    name: 'ฐานที่ 2 Bingo',
    description:
      'Bingo ยกมือขึ้น แล้วพูดว่า บิงโก! เข้าใจเนื้อหา และหลักสูตรพื้นฐานในการเรียนคณะสถาปัตย์ ผ่านคำศัพท์ 24 คำที่คัดมาแล้วว่าสุด!',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'คอร์ทไผ่ คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw6',
    name: 'ฐานที่ 3 Dream',
    description:
      'Dream เมื่อคุณดันหลุดเข้าไปในห้อง… แล้วเจอเข้ากับอะไรแปลก ๆ ที่ไม่ควรมีอยู๋ในนั้น มาจำลอง จินตนาการ ผ่านแนวคิดของที่ควรมีและของแปลก ๆ ที่ไม่ควรมีในห้องและสถานที่ต่าง ๆ ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'ห้องสมาคมศิษย์เก่า คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw7',
    name: 'ฐานที่ 4 The line',
    description:
      'the Line ขีดเพียง 1 เส้น ให้กาลครั้งหนึ่งนั้นยาวนานขึ้น พื้นที่ปลดปล่อยจินตนาการ การสร้างสรรค์ และภาพจำในวัตถุทรงจำที่ต่างกันไปของแต่ละคน ผ่านการขึดและเขียนลงบนผืนผ้าใบ ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'คอร์ทไผ่ คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw8',
    name: 'ฐานที่ 5 Heartrate',
    description:
      'Heart Rates ตึกตักตึกตัก ดันถูกใจเข้าแล้วซี ประเมินและวิพากษ์เมืองในแง่ของการเสนอความเป็นไปได้ใหม่ ในการมีพื้นที่สาธารณะที่ทุกคนเข้าถึงได้',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'คอร์ทไผ่ คณะสถาปัตยกรรมศาสตร์',
    locationURL: 'https://maps.app.goo.gl/mcVQqhWU4okDy3Ae8',
  },
  {
    id: 'archw9',
    name: 'Arch Craft @ศาลาพระเกี๊ยว',
    description:
      'กิจกรรมพิเศษ แล้วมาสร้างบ้านไปด้วยกันนะ! ได้ของติดมือกลับไปกันทุกคนแน่นอน โดยนิสิตชั้นปีที่ 2-3 จากหลักสูตรนานาชาติ CommDe และ INDA',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/arsc.chula',
    faculty: 'arch',
    timeSlot: '09.00 - 16:00',
    locationName: 'ศาสาพระเกี้ยว',
  },

  // คณะสหเวชศาสตร์
  {
    id: 'ahsw1',
    name: 'Workshop MT',
    description:
      'ใครสงสัยยกมือขึ้น! 🙋‍♀️🙋‍♂️ \n❓ นักเทคนิคการแพทย์ คือใคร?\n❓ ทำงานยังไง? ตรวจอะไรบ้าง? \n❓ แล้วที่สำคัญ... เรียนจบไปมีงานทำจริงไหม? \nงาน Open House ปีนี้ เปิดโอกาสให้น้อง ๆ มาทำความรู้จักกับ “เทคนิคการแพทย์” หรือบางคนเรียกว่า ""หมอแล็บ"" ที่ใช้ผลแล็บช่วยคุณหมอวินิจฉัยโรค ไม่ว่าจะเป็นการตรวจเลือด สารคัดหลั่งต่าง ๆ การเพาะเชื้อทางจุลชีววิทยา เช่นแบคทีเรีย เชื้อรา ไวรัสก่อโรค และการตรวจไปจนถึงระดับ DNA และยีนได้อีกด้วย',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/ahscuopenhouse',
    faculty: 'ahs',
    timeSlot: '09.00-11.00 / 12.00-14.00 / 15.00-17.00',
    owner: 'เทคนิคการแพทย์',
    locationName: 'โถงอาคารจุฬาพัฒน์ 14',
    locationURL: 'https://maps.app.goo.gl/cJjoXmxtCzLerzQT9',
  },
  {
    id: 'ahsw2',
    name: 'Workshop PT',
    description:
      'เปิดมาด้วย อะไรคือ PT คือศาสตร์ที่ช่วยให้เราสามารถเคลื่อนไหวได้อย่างมีประสิทธิภาพและไม่บาดเจ็บ เราจะเริ่มจากการเรียนรู้ด้าน Motor control รู้หรือไม่ร่างกายเราควบคุมและทำงานประสานด้วยกันได้อย่างไรถ้าคนเราเคลื่อนไหวผิดแปลกไปร่างกายเราจะตอบสนองอย่างไรบ้าง  เมื่อเราใช้ร่างกายหนักๆ เราก็อาจจะมีอาการปวด เมื่อยหรือ บวมได้ เรามาต่อกันเลยดีกว่าที่ Electrical Stimulation (ES) เป็นการใช้กระแสไฟฟ้าเพื่อลดอาการแล้วกระตุ้นกล้ามเนื้อให้ทำงานได้ดีขึ้น ถ้าอยากรู้มากกว่านี้มาลองเข้า Workshop กายภาพกันดูสิ ห้ามพลาด!!',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/ahscuopenhouse',
    faculty: 'ahs',
    timeSlot: '09.00-11.00 / 12.00-14.00 / 15.00-17.00',
    owner: 'กายภาพบำบัด',
    locationName: 'โถงอาคารจุฬาพัฒน์ 14',
    locationURL: 'https://maps.app.goo.gl/cJjoXmxtCzLerzQT9',
  },
  {
    id: 'ahsw3',
    name: 'Workshop ND',
    description:
      'สุขภาพดีไม่ได้มาเพราะโชคช่วย แต่มาจากการเลือกกินอย่างมีศาสตร์! โภชนาการและการกำหนดอาหาร  (Nutrition & Dietetics - ND) เป็นศาสตร์ที่ศึกษาความสัมพันธ์ระหว่างอาหารกับสุขภาพ ไม่ใช่แค่เรื่องกินให้อิ่ม แต่คือการกินให้ ""เป๊ะ"" และ ""ปัง"" ต่อสุขภาพ! มาสำรวจบทบาทของนักกำหนดอาหารและเรียนรู้ว่าทำไม ND ถึงเป็นสาขาที่ขาดไม่ได้ ผ่าน 3 ฐานกิจกรรมสุดมันส์',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/ahscuopenhouse',
    faculty: 'ahs',
    timeSlot: '09.00-11.00 / 12.00-14.00 / 15.00-17.00',
    owner: 'โภชนาการและการกำหนดอาหาร',
    locationName: 'โถงอาคารจุฬาพัฒน์ 14',
    locationURL: 'https://maps.app.goo.gl/cJjoXmxtCzLerzQT9',
  },
  {
    id: 'ahsw4',
    name: 'Workshop RT',
    description:
      "เคยสงสัยไหมว่ากว่าจะได้ภาพเอกซเรย์สักใบ ต้องผ่านกระบวนการอะไรบ้าง? มาเปิดโลกสายวิทย์สุขภาพกับสาขา รังสีเทคนิค (RT) ที่จะพาน้อง ๆ ไปสัมผัสบรรยากาศการเรียนแบบเจาะลึก! เริ่มตั้งแต่อุ่นเครื่องพาไปส่องไอเทมลับของนักรังสี ก่อนจะพาดำดิ่งไปทำความเข้าใจว่า 'รังสี' ที่เราได้ยินกันบ่อย ๆ คืออะไรกันแน่ พร้อมไขข้อข้องใจสารพัดความเชื่อเรื่องรังสี... อันไหนเรื่องจริง อันไหนแค่ข่าวลือ เดี๋ยวรู้กัน!",
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/ahscuopenhouse',
    faculty: 'ahs',
    timeSlot: '09.00-11.00 / 12.00-14.00 / 15.00-17.00',
    owner: 'รังสีเทคนิค',
    locationName: 'โถงอาคารจุฬาพัฒน์ 14',
    locationURL: 'https://maps.app.goo.gl/cJjoXmxtCzLerzQT9',
  },
  {
    id: 'ahsw5',
    name: 'นิทรรศการแต่ละสาขาของสหเวชฯ',
    description:
      '🔬 MT (เทคนิคการแพทย์) – โลกของห้องแล็บที่เต็มไปด้วยการตรวจวิเคราะห์ทางการแพทย์ ตั้งแต่เลือด ปัสสาวะ ไปจนถึงจุลชีววิทยา \n🦴 PT (กายภาพบำบัด) – ศาสตร์แห่งการฟื้นฟูร่างกาย เรียนรู้เกี่ยวกับโครงสร้างร่างกาย การเคลื่อนไหว และเทคนิคบำบัดต่างๆ \n🥗 ND (โภชนาการและการกำหนดอาหาร) – เข้าใจโภชนาการที่เหมาะสม บทบาทของนักกำหนดอาหาร และผลของอาหารต่อสุขภาพ \n☢️ RT (รังสีเทคนิค) – เปิดโลกของรังสีทางการแพทย์ การสร้างภาพเอกซเรย์ และความปลอดภัยทางรังสี \n✨ แล้วมาดูกันว่าสาขาไหนใช่สำหรับน้อง ๆ! 🎉🔥',
    hasPreregistered: false,
    hasLimitParticipants: false,
    faculty: 'ahs',
    timeSlot: '08:30 - 16:30',
    locationName: 'โถงอาคารจุฬาพัฒน์ 14',
    locationURL: 'https://maps.app.goo.gl/cJjoXmxtCzLerzQT9',
  },

  // คณะสัตวแพทยศาสตร์
  {
    id: 'vetw1',
    name: 'แนะแนว by รุ่นพี่ cuvet',
    description:
      'กิจกรรมแนะแนวสุดพิเศษ เจาะลึกวิธีการเข้าแต่ละรอบไม่ว่าจะเป็น portfolio, quota หรือ admission  รวมไปถึงแนะแนวการเรียนการสอนภายในคณะโดยรุ่นพี่สัตวแพทย์จุฬา',
    hasPreregistered: true,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/cuvetopenhouse',
    faculty: 'vet',
    timeSlot: '8:30 - 12:00 / 13:00 - 16:00',
  },
  {
    id: 'vetw2',
    name: 'workshop เจาะเลือด/ฉีดวัคซีน',
    description:
      'สอนวิธีการเจาะเลือด/ฉีดวัคซีนที่ถูกต้อง ซึ่งเป็นหัตถการหลักในวิชาชีพสัตวแพทย์',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuvetopenhouse',
    faculty: 'vet',
  },
  {
    id: 'vetw3',
    name: 'workshop demon anatomy',
    description:
      'demon ร่างอาจารย์ใหญ่ให้ดูแบบ exclusive น้องๆจะได้เห็นวิธีการผ่าร่างอาจารย์ใหญ่ รวมไปถึงศึกษาอนาโตมีเบื้องต้น',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuvetopenhouse',
    faculty: 'vet',
    timeSlot: '8.30-9.00 / 13.00-13.30',
  },
  {
    id: 'vetw4',
    name: 'workshop aseptic techniques/เย็บแผล',
    description:
      'น้องๆจะได้ฝึกล้างมือแบบศัลยแพทย์ และได้ลองฝึกเย็บแผลจากแป้นเย็บ โดยมีพี่ๆคอยสอน',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/cuvetopenhouse',
    faculty: 'vet',
  },
  {
    id: 'vetw5',
    name: 'ทัวร์คณะ',
    description:
      'น้องๆสามารถเดินดูตามห้องที่มีการจัดนิทรรศการได้ เช่นที่คอกสัตว์ หรือห้องแลปวิชาปรสิตที่มีตัวอย่างตั้งไว้ให้ดู',
    hasPreregistered: false,
    hasLimitParticipants: false,
    faculty: 'vet',
  },
  {
    id: 'vetw6',
    name: 'บรรยายพิเศษโดยวิทยากร',
    description:
      'น้องๆจะได้รับฟังการบรรยายหัวข้อต่างๆโดนวิทยากรรับเชิญ ไม่ว่าจะเป็นเกี่ยวกับสายอาชีพต่างๆหรือกิจกรรมภายในคณะ',
    hasPreregistered: false,
    hasLimitParticipants: false,
    faculty: 'vet',
  },
  {
    id: 'vetw7',
    name: 'walk rally',
    description:
      'น้องๆจะได้รับกระดาษเพื่อไปวนฐาน walk rally ซึ่งจะจัดโดยค่าย/ชมรมต่างๆภายในคณะ เพื่อให้น้องๆได้รู้ว่ามีกิจกรรมและชมรมใดบ้าง',
    hasPreregistered: false,
    hasLimitParticipants: false,
    faculty: 'vet',
  },

  // คณะอักษรศาสตร์
  {
    id: 'artsw1',
    name: 'นิทรรศการกลางและห้องแนะแนว',
    description:
      'กิจกรรมสุดคุ้มที่รวมนิทรรศการกลาง พื้นที่แห่งการค้นหาความเป็นอักษรผ่านกิจกรรมร่วมสนุกมากมาย และห้องแนะแนว พื้นที่นำเสนอข้อมูลทางวิชาการเบื้องต้นและได้พูดคุยกับนิสิตคณะอักษรศาสตร์โดยตรง',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/artsopenhouse',
    faculty: 'arts',
    timeSlot: '10:00-16:00',
    locationName: 'ห้อง 303-304 อาคารมหาจักรีสิรินธร',
    locationURL: 'https://maps.app.goo.gl/LA1CoWkhnfnjKExj7',
  },
  {
    id: 'artsw2',
    name: 'Walk Rally',
    description:
      'รับพาสปอร์ตแล้วออกเดินทางไปพร้อมกัน กับกิจกรรมที่เปิดโอกาสให้ผู้เข้าร่วมสำรวจพื้นที่ภายในงาน ผ่านการร่วมกิจกรรมตามจุดต่าง ๆ สะสมตราประทับประจำแต่ละจุดให้ครบ แล้วลุ้นรับของรางวัลพิเศษไปเลย !',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/artsopenhouse',
    faculty: 'arts',
    timeSlot: '10:00-16:00',
    locationURL: 'https://maps.app.goo.gl/LA1CoWkhnfnjKExj7',
  },
  {
    id: 'artsw3',
    name: 'ห้องเรียนจำลอง',
    description:
      'เปิดให้น้อง ๆ ได้ทดลองมานั่งเรียนวิชาต่าง ๆ ที่จัดสอนจริงในคณะอักษรศาสตร์ โดยอาจารย์ผู้สอนจริงตามสาขาวิชานั้น เป็นเวลา 90 นาที',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.ticketmelon.com/AksornCUopenhouse/HongRienJamLong',
    faculty: 'arts',
    timeSlot: '10:15-11:45 / 12:15-13:45 / 14:15-15:45',
    locationName: 'ห้อง 301-302 อาคารมหาจักรีสิรินธร',
    locationURL: 'https://maps.app.goo.gl/LA1CoWkhnfnjKExj7',
  },
  {
    id: 'artsw4',
    name: 'เวทีกลาง',
    description:
      'เป็นเวทีที่ให้ชมรมต่าง ๆ จากคณะอักษรศาสตร์มาแสดงความสามารถ ไม่ว่าจะเป็นทางด้านดนตรี ร้อง เล่น เต้น รำ และ โต้วาทีเพื่อให้น้อง ๆ ได้รับชม',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/artsopenhouse',
    faculty: 'arts',
    timeSlot: '10:00-16:00',
    locationName: 'โถงอาคารมหาจักรีสิรินธร',
    locationURL: 'https://maps.app.goo.gl/LA1CoWkhnfnjKExj7',
  },
  {
    id: 'artsw5',
    name: 'ห้องเอก-โท',
    description:
      'กิจกรรมห้องเอก-โทจะพาน้อง ๆ ไปทำความรู้จักกับวิชาเอกและวิชาโทในคณะอักษรศาสตร์อย่างครบถ้วน ด้วยบรรยากาศเป็นกันเองจากพี่ ๆ แต่ละเอก-โท',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/artsopenhouse',
    faculty: 'arts',
    timeSlot: '10:00-16:00',
    locationName: 'อาคารมหาจักรีสิรินธร',
    locationURL: 'https://maps.app.goo.gl/LA1CoWkhnfnjKExj7',
  },

  // สถาบันนวัตกรรมบูรณาการแห่งจุฬาลงกรณ์มหาวิทยาลัย
  {
    id: 'sciiw1',
    name: 'Workshop 1 - The Power of Prototyping: From Idea to Reality',
    description:
      'Discover how innovators turn ideas into reality through rapid prototyping. In this hands-on workshop, you will build, test, and improve a solution to a real-world challenge.',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '28 March: 11:00 - 11:45 / 28 March: 13:00 - 13:45',
    locationName: 'Fablab, Fl. 4, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw2',
    name: 'Workshop 2 - How to Beat the System',
    description:
      'Can your team turn chaos into flow? Compete to make a system faster, smoother, and smarter, then learn the simple “why” behind what worked.',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '28 March: 11:00 - 11:45 / 28 March: 13:00 - 13:45',
    locationName: 'Room 409, Fl. 4, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw3',
    name: 'Workshop 3 - How to Run a Service like Shinkansen',
    description:
      "Want customers to trust your business? Learn the rules of operational transparency, then discover the behind-the-scenes system that keeps Japan's Shinkansen clean and always on time.",
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '29 March: 11:00 - 11:45 / 29 March: 13:00 - 13:45',
    locationName: 'Room 409, Fl. 4, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw4',
    name: 'Workshop 4 - Thai Herbal Mosquito Repellent Spray',
    description:
      'Create a Thai herbal mosquito repellent spray using ingredients like citronella and lemongrass. Through hands-on activities, they learn basic extraction, formulation, and product design, connecting science, innovation, and Thai wisdom.',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '29 March: 11:00 - 11:45 / 29 March: 13:00 - 13:45',
    locationName: 'Fablab, Fl. 4, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw5',
    name: "Parents' Session",
    description:
      'A comfortable space for parents to relax while their children explore the Open House independently. Faculty members are available for casual conversations to share insights on BAScii’s curriculum, student life, and admissions.',
    hasPreregistered: true,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '11:00 - 11:45 / 13:00 - 13:45',
    locationName: 'Auditorium, Fl. 3, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw6',
    name: 'Showcase',
    description:
      'An open display of student-led projects, startups, clubs, and houses that showcases the vibrant BAScii community. Visitors can meet students behind the initiatives and explore the diverse pathways BAScii offers.',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '09:00 - 16:00',
    locationName: 'Fl. 1, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw7',
    name: 'Tour Guide',
    description:
      'A personalized Q&A space where participants can speak directly with BAScii students and tour guides for honest, first-hand insights on academics and student life, helping them understand whether BAScii fits their goals.',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '09:00 - 16:00',
    locationName: 'Fl. 1, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  {
    id: 'sciiw8',
    name: 'Exhibition',
    description:
      'A curated walk-through experience introducing BAScii’s culture, curriculum, and innovation ecosystem through interactive displays and storytelling, helping students visualize their future academic journey.',
    hasPreregistered: false,
    hasLimitParticipants: false,
    url: 'https://www.instagram.com/basciiscofficial',
    faculty: 'scii',
    timeSlot: '09:00 - 16:00',
    locationName: 'Room 301-302, Fl. 3, Chaloem Rajakumari 60',
    locationURL: 'https://share.google/T2iSSvPKtpo3RhKL3',
  },
  // คณะเกษตรศาสตร์บูรณาการ
  {
    id: 'cusarw1',
    name: 'สวนขวดในใจเธอ',
    description:
      'Workshop ที่อยากให้ทุกคนได้ลองจัดสวนขวดของคุณเอง จำลองสวนขนาดเล็กที่ดูแลไม่ยาก เหมาะสำหรับคนที่อยากทดลองการปลูกต้นไม้ แต่ไม่รู้จะเริ่มยังไง ใช่ทางที่คุณชอบหรือเปล่า ?',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://docs.google.com/forms/d/e/1FAIpQLSeuU8_iUK8A1uOYWVQiannHkyb2oyUki43-tMLvZDUbwIglSg/viewform',
    faculty: 'cusar',
    timeSlot: '9.00 - 12.00 / 13.00 - 16.00',
    locationName: 'ใต้โถงอาคารจุฬาพัฒน์ 13',
    locationURL: 'https://maps.app.goo.gl/nNuRFHVKEbq7gwur5?g_st=ic',
  },
  {
    id: 'cusarw2',
    name: 'กลิ่นนำทาง',
    description:
      'Workshop ธุรกิจกลางน้ำ ที่นำสารสกัดการพืช สมุนไพร ดอกไม้ มาปรุงกลิ่นที่มีเอกลักษณ์และทำให้กับตัวเองสุดจะมีคุณค่า พบได้แค่งานนี้งานเดียวเท่านั้น',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://docs.google.com/forms/d/e/1FAIpQLSeuU8_iUK8A1uOYWVQiannHkyb2oyUki43-tMLvZDUbwIglSg/viewform',
    faculty: 'cusar',
    timeSlot: '9.00 - 12.00 / 13.00 - 16.00',
    locationName: 'ใต้โถงอาคารจุฬาพัฒน์ 13',
    locationURL: 'https://maps.app.goo.gl/nNuRFHVKEbq7gwur5?g_st=ic',
  },
  // หอพักนิสิตจุฬาลงกรณ์มหาวิทยาลัย
  {
    id: 'dormw1',
    name: 'พาทัวร์หอใน',
    description:
      'พาน้อง ๆ ที่สนใจหอพักนิสิตไปเยี่ยมชมบริเวณหอพักนิสิต และให้ข้อมูลต่าง ๆ เกี่ยวกับหอพักแต่ละหอ',
    hasPreregistered: true,
    hasLimitParticipants: true,
    url: 'https://www.instagram.com/rcusc.chula',
    faculty: 'dorm',
    timeSlot: '11:00-12:00 / 14:00-15:00',
    locationName: 'เริ่มเดินตั้งแต่ทางเข้าฝั่งพญาไท ถึง ทางเข้าฝั่งป้ายรถปอ.พ.',
    locationURL: 'https://maps.app.goo.gl/92dN5pM5WBuPH5gq8?g_st=ac',
  },
]
