/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteRouteImport } from './routes/game/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as QuestionaireIndexRouteImport } from './routes/questionaire/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as CertificateIndexRouteImport } from './routes/certificate/index'
import { Route as InfoWorkshopIndexRouteImport } from './routes/info/workshop/index'
import { Route as InfoMerchandiseIndexRouteImport } from './routes/info/merchandise/index'
import { Route as InfoMapIndexRouteImport } from './routes/info/map/index'
import { Route as InfoFacultyIndexRouteImport } from './routes/info/faculty/index'
import { Route as GameShareIndexRouteImport } from './routes/game/share/index'
import { Route as GamePieceIndexRouteImport } from './routes/game/piece/index'
import { Route as GameAchievementIndexRouteImport } from './routes/game/achievement/index'
import { Route as AuthQrIndexRouteImport } from './routes/auth/qr/index'
import { Route as AuthProfileIndexRouteImport } from './routes/auth/profile/index'
import { Route as AuthOnboardingIndexRouteImport } from './routes/auth/onboarding/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as InfoWorkshopWorkshopIdIndexRouteImport } from './routes/info/workshop/$workshopId/index'
import { Route as InfoFacultyFacultyIdIndexRouteImport } from './routes/info/faculty/$facultyId/index'
import { Route as AuthStaffOnboardingIndexRouteImport } from './routes/auth/staff/onboarding/index'
import { Route as AuthStaffLoginIndexRouteImport } from './routes/auth/staff/login/index'
import { Route as AuthProfileTicketIndexRouteImport } from './routes/auth/profile/ticket/index'
import { Route as AuthProfileEditIndexRouteImport } from './routes/auth/profile/edit/index'

const GameRouteRoute = GameRouteRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionaireIndexRoute = QuestionaireIndexRouteImport.update({
  id: '/questionaire/',
  path: '/questionaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRouteRoute,
} as any)
const CertificateIndexRoute = CertificateIndexRouteImport.update({
  id: '/certificate/',
  path: '/certificate/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoWorkshopIndexRoute = InfoWorkshopIndexRouteImport.update({
  id: '/info/workshop/',
  path: '/info/workshop/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoMerchandiseIndexRoute = InfoMerchandiseIndexRouteImport.update({
  id: '/info/merchandise/',
  path: '/info/merchandise/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoMapIndexRoute = InfoMapIndexRouteImport.update({
  id: '/info/map/',
  path: '/info/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoFacultyIndexRoute = InfoFacultyIndexRouteImport.update({
  id: '/info/faculty/',
  path: '/info/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameShareIndexRoute = GameShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => GameRouteRoute,
} as any)
const GamePieceIndexRoute = GamePieceIndexRouteImport.update({
  id: '/piece/',
  path: '/piece/',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameAchievementIndexRoute = GameAchievementIndexRouteImport.update({
  id: '/achievement/',
  path: '/achievement/',
  getParentRoute: () => GameRouteRoute,
} as any)
const AuthQrIndexRoute = AuthQrIndexRouteImport.update({
  id: '/auth/qr/',
  path: '/auth/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/auth/profile/',
  path: '/auth/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/auth/onboarding/',
  path: '/auth/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoWorkshopWorkshopIdIndexRoute =
  InfoWorkshopWorkshopIdIndexRouteImport.update({
    id: '/info/workshop/$workshopId/',
    path: '/info/workshop/$workshopId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoFacultyFacultyIdIndexRoute =
  InfoFacultyFacultyIdIndexRouteImport.update({
    id: '/info/faculty/$facultyId/',
    path: '/info/faculty/$facultyId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthStaffOnboardingIndexRoute =
  AuthStaffOnboardingIndexRouteImport.update({
    id: '/auth/staff/onboarding/',
    path: '/auth/staff/onboarding/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthStaffLoginIndexRoute = AuthStaffLoginIndexRouteImport.update({
  id: '/auth/staff/login/',
  path: '/auth/staff/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileTicketIndexRoute = AuthProfileTicketIndexRouteImport.update({
  id: '/auth/profile/ticket/',
  path: '/auth/profile/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileEditIndexRoute = AuthProfileEditIndexRouteImport.update({
  id: '/auth/profile/edit/',
  path: '/auth/profile/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRouteRouteWithChildren
  '/certificate/': typeof CertificateIndexRoute
  '/game/': typeof GameIndexRoute
  '/questionaire/': typeof QuestionaireIndexRoute
  '/test/': typeof TestIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/auth/qr/': typeof AuthQrIndexRoute
  '/game/achievement/': typeof GameAchievementIndexRoute
  '/game/piece/': typeof GamePieceIndexRoute
  '/game/share/': typeof GameShareIndexRoute
  '/info/faculty/': typeof InfoFacultyIndexRoute
  '/info/map/': typeof InfoMapIndexRoute
  '/info/merchandise/': typeof InfoMerchandiseIndexRoute
  '/info/workshop/': typeof InfoWorkshopIndexRoute
  '/auth/profile/edit/': typeof AuthProfileEditIndexRoute
  '/auth/profile/ticket/': typeof AuthProfileTicketIndexRoute
  '/auth/staff/login/': typeof AuthStaffLoginIndexRoute
  '/auth/staff/onboarding/': typeof AuthStaffOnboardingIndexRoute
  '/info/faculty/$facultyId/': typeof InfoFacultyFacultyIdIndexRoute
  '/info/workshop/$workshopId/': typeof InfoWorkshopWorkshopIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateIndexRoute
  '/game': typeof GameIndexRoute
  '/questionaire': typeof QuestionaireIndexRoute
  '/test': typeof TestIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
  '/auth/profile': typeof AuthProfileIndexRoute
  '/auth/qr': typeof AuthQrIndexRoute
  '/game/achievement': typeof GameAchievementIndexRoute
  '/game/piece': typeof GamePieceIndexRoute
  '/game/share': typeof GameShareIndexRoute
  '/info/faculty': typeof InfoFacultyIndexRoute
  '/info/map': typeof InfoMapIndexRoute
  '/info/merchandise': typeof InfoMerchandiseIndexRoute
  '/info/workshop': typeof InfoWorkshopIndexRoute
  '/auth/profile/edit': typeof AuthProfileEditIndexRoute
  '/auth/profile/ticket': typeof AuthProfileTicketIndexRoute
  '/auth/staff/login': typeof AuthStaffLoginIndexRoute
  '/auth/staff/onboarding': typeof AuthStaffOnboardingIndexRoute
  '/info/faculty/$facultyId': typeof InfoFacultyFacultyIdIndexRoute
  '/info/workshop/$workshopId': typeof InfoWorkshopWorkshopIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRouteRouteWithChildren
  '/certificate/': typeof CertificateIndexRoute
  '/game/': typeof GameIndexRoute
  '/questionaire/': typeof QuestionaireIndexRoute
  '/test/': typeof TestIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/auth/qr/': typeof AuthQrIndexRoute
  '/game/achievement/': typeof GameAchievementIndexRoute
  '/game/piece/': typeof GamePieceIndexRoute
  '/game/share/': typeof GameShareIndexRoute
  '/info/faculty/': typeof InfoFacultyIndexRoute
  '/info/map/': typeof InfoMapIndexRoute
  '/info/merchandise/': typeof InfoMerchandiseIndexRoute
  '/info/workshop/': typeof InfoWorkshopIndexRoute
  '/auth/profile/edit/': typeof AuthProfileEditIndexRoute
  '/auth/profile/ticket/': typeof AuthProfileTicketIndexRoute
  '/auth/staff/login/': typeof AuthStaffLoginIndexRoute
  '/auth/staff/onboarding/': typeof AuthStaffOnboardingIndexRoute
  '/info/faculty/$facultyId/': typeof InfoFacultyFacultyIdIndexRoute
  '/info/workshop/$workshopId/': typeof InfoWorkshopWorkshopIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/certificate/'
    | '/game/'
    | '/questionaire/'
    | '/test/'
    | '/auth/login/'
    | '/auth/onboarding/'
    | '/auth/profile/'
    | '/auth/qr/'
    | '/game/achievement/'
    | '/game/piece/'
    | '/game/share/'
    | '/info/faculty/'
    | '/info/map/'
    | '/info/merchandise/'
    | '/info/workshop/'
    | '/auth/profile/edit/'
    | '/auth/profile/ticket/'
    | '/auth/staff/login/'
    | '/auth/staff/onboarding/'
    | '/info/faculty/$facultyId/'
    | '/info/workshop/$workshopId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/game'
    | '/questionaire'
    | '/test'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/profile'
    | '/auth/qr'
    | '/game/achievement'
    | '/game/piece'
    | '/game/share'
    | '/info/faculty'
    | '/info/map'
    | '/info/merchandise'
    | '/info/workshop'
    | '/auth/profile/edit'
    | '/auth/profile/ticket'
    | '/auth/staff/login'
    | '/auth/staff/onboarding'
    | '/info/faculty/$facultyId'
    | '/info/workshop/$workshopId'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/certificate/'
    | '/game/'
    | '/questionaire/'
    | '/test/'
    | '/auth/login/'
    | '/auth/onboarding/'
    | '/auth/profile/'
    | '/auth/qr/'
    | '/game/achievement/'
    | '/game/piece/'
    | '/game/share/'
    | '/info/faculty/'
    | '/info/map/'
    | '/info/merchandise/'
    | '/info/workshop/'
    | '/auth/profile/edit/'
    | '/auth/profile/ticket/'
    | '/auth/staff/login/'
    | '/auth/staff/onboarding/'
    | '/info/faculty/$facultyId/'
    | '/info/workshop/$workshopId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRouteRoute: typeof GameRouteRouteWithChildren
  CertificateIndexRoute: typeof CertificateIndexRoute
  QuestionaireIndexRoute: typeof QuestionaireIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthQrIndexRoute: typeof AuthQrIndexRoute
  InfoFacultyIndexRoute: typeof InfoFacultyIndexRoute
  InfoMapIndexRoute: typeof InfoMapIndexRoute
  InfoMerchandiseIndexRoute: typeof InfoMerchandiseIndexRoute
  InfoWorkshopIndexRoute: typeof InfoWorkshopIndexRoute
  AuthProfileEditIndexRoute: typeof AuthProfileEditIndexRoute
  AuthProfileTicketIndexRoute: typeof AuthProfileTicketIndexRoute
  AuthStaffLoginIndexRoute: typeof AuthStaffLoginIndexRoute
  AuthStaffOnboardingIndexRoute: typeof AuthStaffOnboardingIndexRoute
  InfoFacultyFacultyIdIndexRoute: typeof InfoFacultyFacultyIdIndexRoute
  InfoWorkshopWorkshopIdIndexRoute: typeof InfoWorkshopWorkshopIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionaire/': {
      id: '/questionaire/'
      path: '/questionaire'
      fullPath: '/questionaire/'
      preLoaderRoute: typeof QuestionaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/certificate/': {
      id: '/certificate/'
      path: '/certificate'
      fullPath: '/certificate/'
      preLoaderRoute: typeof CertificateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/workshop/': {
      id: '/info/workshop/'
      path: '/info/workshop'
      fullPath: '/info/workshop/'
      preLoaderRoute: typeof InfoWorkshopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/merchandise/': {
      id: '/info/merchandise/'
      path: '/info/merchandise'
      fullPath: '/info/merchandise/'
      preLoaderRoute: typeof InfoMerchandiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/map/': {
      id: '/info/map/'
      path: '/info/map'
      fullPath: '/info/map/'
      preLoaderRoute: typeof InfoMapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/faculty/': {
      id: '/info/faculty/'
      path: '/info/faculty'
      fullPath: '/info/faculty/'
      preLoaderRoute: typeof InfoFacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/share/': {
      id: '/game/share/'
      path: '/share'
      fullPath: '/game/share/'
      preLoaderRoute: typeof GameShareIndexRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/game/piece/': {
      id: '/game/piece/'
      path: '/piece'
      fullPath: '/game/piece/'
      preLoaderRoute: typeof GamePieceIndexRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/game/achievement/': {
      id: '/game/achievement/'
      path: '/achievement'
      fullPath: '/game/achievement/'
      preLoaderRoute: typeof GameAchievementIndexRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/auth/qr/': {
      id: '/auth/qr/'
      path: '/auth/qr'
      fullPath: '/auth/qr/'
      preLoaderRoute: typeof AuthQrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile/': {
      id: '/auth/profile/'
      path: '/auth/profile'
      fullPath: '/auth/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding/': {
      id: '/auth/onboarding/'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/workshop/$workshopId/': {
      id: '/info/workshop/$workshopId/'
      path: '/info/workshop/$workshopId'
      fullPath: '/info/workshop/$workshopId/'
      preLoaderRoute: typeof InfoWorkshopWorkshopIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/faculty/$facultyId/': {
      id: '/info/faculty/$facultyId/'
      path: '/info/faculty/$facultyId'
      fullPath: '/info/faculty/$facultyId/'
      preLoaderRoute: typeof InfoFacultyFacultyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/staff/onboarding/': {
      id: '/auth/staff/onboarding/'
      path: '/auth/staff/onboarding'
      fullPath: '/auth/staff/onboarding/'
      preLoaderRoute: typeof AuthStaffOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/staff/login/': {
      id: '/auth/staff/login/'
      path: '/auth/staff/login'
      fullPath: '/auth/staff/login/'
      preLoaderRoute: typeof AuthStaffLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile/ticket/': {
      id: '/auth/profile/ticket/'
      path: '/auth/profile/ticket'
      fullPath: '/auth/profile/ticket/'
      preLoaderRoute: typeof AuthProfileTicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile/edit/': {
      id: '/auth/profile/edit/'
      path: '/auth/profile/edit'
      fullPath: '/auth/profile/edit/'
      preLoaderRoute: typeof AuthProfileEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GameRouteRouteChildren {
  GameIndexRoute: typeof GameIndexRoute
  GameAchievementIndexRoute: typeof GameAchievementIndexRoute
  GamePieceIndexRoute: typeof GamePieceIndexRoute
  GameShareIndexRoute: typeof GameShareIndexRoute
}

const GameRouteRouteChildren: GameRouteRouteChildren = {
  GameIndexRoute: GameIndexRoute,
  GameAchievementIndexRoute: GameAchievementIndexRoute,
  GamePieceIndexRoute: GamePieceIndexRoute,
  GameShareIndexRoute: GameShareIndexRoute,
}

const GameRouteRouteWithChildren = GameRouteRoute._addFileChildren(
  GameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRouteRoute: GameRouteRouteWithChildren,
  CertificateIndexRoute: CertificateIndexRoute,
  QuestionaireIndexRoute: QuestionaireIndexRoute,
  TestIndexRoute: TestIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthQrIndexRoute: AuthQrIndexRoute,
  InfoFacultyIndexRoute: InfoFacultyIndexRoute,
  InfoMapIndexRoute: InfoMapIndexRoute,
  InfoMerchandiseIndexRoute: InfoMerchandiseIndexRoute,
  InfoWorkshopIndexRoute: InfoWorkshopIndexRoute,
  AuthProfileEditIndexRoute: AuthProfileEditIndexRoute,
  AuthProfileTicketIndexRoute: AuthProfileTicketIndexRoute,
  AuthStaffLoginIndexRoute: AuthStaffLoginIndexRoute,
  AuthStaffOnboardingIndexRoute: AuthStaffOnboardingIndexRoute,
  InfoFacultyFacultyIdIndexRoute: InfoFacultyFacultyIdIndexRoute,
  InfoWorkshopWorkshopIdIndexRoute: InfoWorkshopWorkshopIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
