/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as InfoIndexRouteImport } from './routes/info/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as TestNameRouteImport } from './routes/test/$name'
import { Route as TestComponentIndexRouteImport } from './routes/test/component/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoIndexRoute = InfoIndexRouteImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNameRoute = TestNameRouteImport.update({
  id: '/test/$name',
  path: '/test/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const TestComponentIndexRoute = TestComponentIndexRouteImport.update({
  id: '/test/component/',
  path: '/test/component/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/$name': typeof TestNameRoute
  '/game/': typeof GameIndexRoute
  '/info/': typeof InfoIndexRoute
  '/test/': typeof TestIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/test/component/': typeof TestComponentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/$name': typeof TestNameRoute
  '/game': typeof GameIndexRoute
  '/info': typeof InfoIndexRoute
  '/test': typeof TestIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/test/component': typeof TestComponentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test/$name': typeof TestNameRoute
  '/game/': typeof GameIndexRoute
  '/info/': typeof InfoIndexRoute
  '/test/': typeof TestIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/test/component/': typeof TestComponentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test/$name'
    | '/game/'
    | '/info/'
    | '/test/'
    | '/auth/login/'
    | '/test/component/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/$name'
    | '/game'
    | '/info'
    | '/test'
    | '/auth/login'
    | '/test/component'
  id:
    | '__root__'
    | '/'
    | '/test/$name'
    | '/game/'
    | '/info/'
    | '/test/'
    | '/auth/login/'
    | '/test/component/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestNameRoute: typeof TestNameRoute
  GameIndexRoute: typeof GameIndexRoute
  InfoIndexRoute: typeof InfoIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  TestComponentIndexRoute: typeof TestComponentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/': {
      id: '/info/'
      path: '/info'
      fullPath: '/info/'
      preLoaderRoute: typeof InfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$name': {
      id: '/test/$name'
      path: '/test/$name'
      fullPath: '/test/$name'
      preLoaderRoute: typeof TestNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/component/': {
      id: '/test/component/'
      path: '/test/component'
      fullPath: '/test/component/'
      preLoaderRoute: typeof TestComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestNameRoute: TestNameRoute,
  GameIndexRoute: GameIndexRoute,
  InfoIndexRoute: InfoIndexRoute,
  TestIndexRoute: TestIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  TestComponentIndexRoute: TestComponentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
